### PR TITLE
K8SPXC-798 Replace deprecated Kubernetes APIs

### PR DESCRIPTION
**Pull request by hors**
[K8SPXC-798](https://jira.percona.com/browse/K8SPXC-798) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by delgod — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | failed |
| scheduled-backup | failed |
| storage | failed |
| recreate | failed |
| scaling | failed |
| haproxy | failed |
| big-data | failed |
| self-healing | failed |
| scaling-proxysql | failed |
| restore-to-encrypted-cluster | failed |
| init-deploy | failed |
| self-healing-chaos | failed |
| security-context | failed |
| demand-backup | failed |
| limits | failed |
| self-healing-advanced | failed |
| pitr | failed |
| monitoring-2-0 | failed |
| self-healing-advanced-chaos | failed |
| affinity | failed |
| demand-backup-encrypted-with-tls | failed |
| operator-self-healing | failed |
| one-pod | failed |
| operator-self-healing-chaos | failed |
| upgrade-proxysql | failed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | failed |
| users | failed |
| tls-issue-self | failed |
| tls-issue-cert-manager | failed |
| smart-update | failed |
| tls-issue-cert-manager-ref | failed |
| upgrade-consistency | failed |
| validation-hook | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/911/commits/62ffa74e1ca02be8af3b749746c94f4a0c487ae2
image: `perconalab/percona-xtradb-cluster-operator:PR-911-62ffa74e`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | passed |
| big-data | failed |
| upgrade-haproxy | failed |
| haproxy | passed |
| scaling | passed |
| recreate | passed |
| storage | passed |
| scaling-proxysql | passed |
| self-healing | failed |
| init-deploy | failed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| limits | passed |
| upgrade-proxysql | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| self-healing-chaos | failed |
| affinity | passed |
| smart-update | failed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| users | passed |
| operator-self-healing-chaos | failed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/911/commits/5ee1b18fc82a6038581b9ba7e05dac2b01d006ca
image: `perconalab/percona-xtradb-cluster-operator:PR-911-5ee1b18f`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| storage | passed |
| scheduled-backup | passed |
| scaling | passed |
| recreate | passed |
| haproxy | passed |
| big-data | failed |
| scaling-proxysql | passed |
| self-healing | passed |
| init-deploy | failed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| self-healing-chaos | failed |
| limits | passed |
| demand-backup | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| smart-update | failed |
| upgrade-consistency | passed |
| affinity | passed |
| self-healing-advanced-chaos | failed |
| one-pod | passed |
| operator-self-healing | passed |
| auto-tuning | passed |
| operator-self-healing-chaos | failed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/911/commits/6051df7a1141d54ff06d8c20aa8678c3cf7a6ea9
image: `perconalab/percona-xtradb-cluster-operator:PR-911-6051df7a`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| storage | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| scheduled-backup | passed |
| recreate | passed |
| big-data | passed |
| scaling-proxysql | passed |
| init-deploy | failed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| self-healing | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-chaos | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| self-healing-advanced | passed |
| affinity | passed |
| one-pod | passed |
| smart-update | failed |
| self-healing-advanced-chaos | passed |
| auto-tuning | passed |
| pitr | passed |
| upgrade-consistency | passed |
| proxysql-sidecar-res-limits | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| demand-backup-encrypted-with-tls | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/911/commits/de071548576f6b3dd7c35e13e5b601755b3f5bc4
image: `perconalab/percona-xtradb-cluster-operator:PR-911-de071548`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| big-data | passed |
| scheduled-backup | passed |
| recreate | passed |
| haproxy | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| self-healing-chaos | passed |
| upgrade-proxysql | failed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| self-healing-advanced | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| self-healing-advanced-chaos | passed |
| smart-update | failed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| operator-self-healing | passed |
| users | passed |
| operator-self-healing-chaos | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | failed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/911/commits/ca125bb06abeb704ed557fa610324684870ed560
image: `perconalab/percona-xtradb-cluster-operator:PR-911-ca125bb0`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| big-data | passed |
| scaling | passed |
| storage | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| security-context | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-haproxy | passed |
| tls-issue-cert-manager-ref | passed |
| upgrade-proxysql | passed |
| validation-hook | passed |
| smart-update | failed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/911/commits/ca125bb06abeb704ed557fa610324684870ed560
image: `perconalab/percona-xtradb-cluster-operator:PR-911-ca125bb0`

**Review by delgod — APPROVED** [review]

**Review by tplavcic — APPROVED** [review]

**Pull request merged**
