### PR TITLE
K8SPXC-895 - Fixes in tests for kubernetes 1.22

### PR DESCRIPTION
**Pull request by tplavcic**
[K8SPXC-895](https://jira.percona.com/browse/K8SPXC-895) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

Here's the test run with 1.22: https://cloud.cd.percona.com/view/PXC/job/pxc-operator-gke-version/810/#showFailuresLink
- 3 chaos-mesh tests failed because chaos-mesh helm chart doesn't support 1.22 yet
- `scheduled-backup` fails a lot so we will probably need to investigate it more (although in the above test run it passed, but after many failures)

Some of the diffs this fixes:
```
+ diff -u /mnt/jenkins/workspace/pxc-operator-gke-latest/source/e2e-tests/proxysql-sidecar-res-limits/compare/service_side-car-proxysql.yml /tmp/tmp.fPAY2stbOt/service_side-car-proxysql.yml
--- /mnt/jenkins/workspace/pxc-operator-gke-latest/source/e2e-tests/proxysql-sidecar-res-limits/compare/service_side-car-proxysql.yml	2021-10-19 00:05:35.000000000 +0000
+++ /tmp/tmp.fPAY2stbOt/service_side-car-proxysql.yml	2021-10-19 01:41:17.990410614 +0000
@@ -14,7 +14,9 @@
       kind: PerconaXtraDBCluster
       name: side-car
 spec:
+  allocateLoadBalancerNodePorts: true
   externalTrafficPolicy: Cluster
+  internalTrafficPolicy: Cluster
   ports:
     - name: mysql
       port: 3306
```

```
+ diff -u /mnt/jenkins/workspace/pxc-operator-gke-latest/source/e2e-tests/security-context/compare/job.batch_xb-on-demand-backup-pvc.yml /tmp/tmp.adrHH7uZmM/job.batch_xb-on-demand-backup-pvc.yml
--- /mnt/jenkins/workspace/pxc-operator-gke-latest/source/e2e-tests/security-context/compare/job.batch_xb-on-demand-backup-pvc.yml	2021-10-19 00:05:35.000000000 +0000
+++ /tmp/tmp.adrHH7uZmM/job.batch_xb-on-demand-backup-pvc.yml	2021-10-19 00:47:01.448299286 +0000
@@ -3,6 +3,7 @@
 metadata:
   annotations:
     openshift.io/scc: privileged
+  generation: 1
   labels:
     cluster: sec-context
     job-name: xb-on-demand-backup-pvc
@@ -14,6 +15,7 @@
       name: on-demand-backup-pvc
 spec:
   backoffLimit: 10
+  completionMode: NonIndexed
   completions: 1
   manualSelector: true
   parallelism: 1
@@ -22,6 +24,7 @@
       cluster: sec-context
       job-name: xb-on-demand-backup-pvc
       type: xtrabackup
+  suspend: false
   template:
     metadata:
       annotations:
```

```
+ diff -u /mnt/jenkins/workspace/cloud-pxc-operator_PR-1023/e2e-tests/init-deploy/compare/service_some-name-proxysql-unready.yml /tmp/tmp.8tUVrddmnN/service_some-name-proxysql-unready.yml
--- /mnt/jenkins/workspace/cloud-pxc-operator_PR-1023/e2e-tests/init-deploy/compare/service_some-name-proxysql-unready.yml	2021-10-19 09:24:27.931233339 +0000
+++ /tmp/tmp.8tUVrddmnN/service_some-name-proxysql-unready.yml	2021-10-19 09:59:57.513813927 +0000
@@ -1,7 +1,6 @@
 apiVersion: v1
 kind: Service
 metadata:
-  annotations: {}
   labels:
     app.kubernetes.io/component: proxysql
     app.kubernetes.io/instance: some-name
```

demand-backup-encrypted-with-tls:
```
error: unable to recognize "/var/folders/fw/lxhtthdn7d9610w5p3wb33340000gn/T/tmp.7TW56kSg/csr.yaml": no matches for kind "CertificateSigningRequest" in version "certificates.k8s.io/v1beta1"

error: error validating "/var/folders/fw/lxhtthdn7d9610w5p3wb33340000gn/T/tmp.4mTk05HK/csr.yaml": error validating data: ValidationError(CertificateSigningRequest.spec): missing required field "signerName" in io.k8s.api.certificates.v1.CertificateSigningRequestSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| scaling | passed |
| upgrade-haproxy | passed |
| scheduled-backup | failed |
| recreate | passed |
| haproxy | passed |
| storage | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| init-deploy | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| one-pod | passed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1023/commits/c250b9513119f97a67745e0c4600cea095bb090f
image: `perconalab/percona-xtradb-cluster-operator:PR-1023-c250b951`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| storage | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| big-data | passed |
| self-healing | passed |
| init-deploy | passed |
| self-healing-chaos | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| self-healing-advanced-chaos | passed |
| scheduled-backup | passed |
| affinity | passed |
| scaling | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| one-pod | passed |
| scaling-proxysql | passed |
| security-context | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1023/commits/c250b9513119f97a67745e0c4600cea095bb090f
image: `perconalab/percona-xtradb-cluster-operator:PR-1023-c250b951`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| recreate | passed |
| haproxy | passed |
| big-data | failed |
| scaling | passed |
| storage | passed |
| scheduled-backup | failed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| init-deploy | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| demand-backup | passed |
| limits | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| smart-update | passed |
| users | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-self | passed |
| upgrade-consistency | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1023/commits/4264646579ca3d7abf8bfd6537d48287800d9261
image: `perconalab/percona-xtradb-cluster-operator:PR-1023-42646465`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| big-data | passed |
| scaling | passed |
| storage | passed |
| recreate | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| limits | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1023/commits/62053d87f2f5bae21ca5de3187a76c057f9f7275
image: `perconalab/percona-xtradb-cluster-operator:PR-1023-62053d87`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| haproxy | passed |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| big-data | passed |
| scaling | passed |
| storage | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1023/commits/8d52c7a23a65788c588105098ac6e36077a2e1f5
image: `perconalab/percona-xtradb-cluster-operator:PR-1023-8d52c7a2`

**Review by delgod — APPROVED** [review]

**Pull request merged**
