### PR TITLE
K8SPXC-941 Exclude old mongo drivers

### PR DESCRIPTION
**Pull request by nonemax**
[K8SPXC-941](https://jira.percona.com/browse/K8SPXC-941) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by delgod — DISMISSED** [review]

**Review by egegunes — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | passed |
| scaling | passed |
| storage | passed |
| recreate | passed |
| haproxy | passed |
| upgrade-haproxy | passed |
| big-data | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| affinity | passed |
| one-pod | passed |
| pitr | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/a764c27767b41e91752d4b9c445570c79045fea0
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-a764c277`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/61d2de4330bcc4c1e628fdda7b83dfc898010d45
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-61d2de43`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| big-data | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| recreate | passed |
| tls-issue-cert-manager-ref | passed |
| restore-to-encrypted-cluster | passed |
| validation-hook | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/a764c27767b41e91752d4b9c445570c79045fea0
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-a764c277`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/3fdd0cc94ce6991c2a5e85b3a2ce5350241966ce
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-3fdd0cc9`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| big-data | passed |
| recreate | passed |
| scheduled-backup | passed |
| storage | passed |
| haproxy | passed |
| upgrade-haproxy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| demand-backup | passed |
| init-deploy | passed |
| smart-update | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| pitr | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| demand-backup-encrypted-with-tls | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/9c84bcab7711797631c0187e14f5638d71433d69
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-9c84bcab`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| storage | passed |
| big-data | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| scaling | passed |
| upgrade-haproxy | passed |
| scaling-proxysql | passed |
| security-context | passed |
| scheduled-backup | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| tls-issue-cert-manager-ref | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| validation-hook | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/9c84bcab7711797631c0187e14f5638d71433d69
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-9c84bcab`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| scheduled-backup | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| scaling | passed |
| big-data | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/9c84bcab7711797631c0187e14f5638d71433d69
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-9c84bcab`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scheduled-backup | passed |
| scaling-proxysql | passed |
| security-context | passed |
| big-data | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/9c84bcab7711797631c0187e14f5638d71433d69
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-9c84bcab`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | passed |
| big-data | passed |
| storage | passed |
| haproxy | passed |
| recreate | passed |
| self-healing | passed |
| init-deploy | passed |
| self-healing-chaos | failed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| pitr | passed |
| affinity | passed |
| scaling-proxysql | passed |
| one-pod | passed |
| demand-backup-encrypted-with-tls | passed |
| auto-tuning | passed |
| security-context | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/9c84bcab7711797631c0187e14f5638d71433d69
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-9c84bcab`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | failed |
| upgrade-haproxy | failed |
| scaling | failed |
| restore-to-encrypted-cluster | failed |
| scaling-proxysql | failed |
| demand-backup | failed |
| security-context | failed |
| pitr | failed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/e43b91950b20f3aa5486e8f2113d82d623d6cb0a
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-e43b9195`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | failed |
| recreate | failed |
| big-data | failed |
| upgrade-haproxy | failed |
| haproxy | failed |
| storage | failed |
| scheduled-backup | failed |
| restore-to-encrypted-cluster | failed |
| scaling-proxysql | failed |
| init-deploy | failed |
| self-healing | passed |
| self-healing-chaos | failed |
| upgrade-proxysql | failed |
| security-context | failed |
| limits | failed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| demand-backup | failed |
| smart-update | failed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| pitr | failed |
| upgrade-consistency | failed |
| affinity | failed |
| demand-backup-encrypted-with-tls | failed |
| one-pod | failed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | failed |
| users | failed |
| tls-issue-self | failed |
| tls-issue-cert-manager | failed |
| tls-issue-cert-manager-ref | failed |
| validation-hook | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/e43b91950b20f3aa5486e8f2113d82d623d6cb0a
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-e43b9195`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | failed |
| big-data | failed |
| recreate | failed |
| storage | failed |
| scaling | failed |
| scheduled-backup | failed |
| haproxy | failed |
| restore-to-encrypted-cluster | failed |
| self-healing | passed |
| self-healing-chaos | failed |
| scaling-proxysql | failed |
| init-deploy | failed |
| upgrade-proxysql | failed |
| demand-backup | failed |
| security-context | failed |
| limits | failed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| smart-update | failed |
| pitr | failed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| upgrade-consistency | failed |
| affinity | failed |
| demand-backup-encrypted-with-tls | failed |
| one-pod | failed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | failed |
| users | failed |
| tls-issue-self | failed |
| tls-issue-cert-manager | failed |
| tls-issue-cert-manager-ref | failed |
| validation-hook | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/e43b91950b20f3aa5486e8f2113d82d623d6cb0a
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-e43b9195`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| big-data | passed |
| scaling | passed |
| recreate | passed |
| storage | passed |
| haproxy | passed |
| scheduled-backup | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| smart-update | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| affinity | passed |
| one-pod | passed |
| pitr | passed |
| auto-tuning | passed |
| upgrade-consistency | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/b38a9f258672c83457a9c87afc2b556498a2f2dc
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-b38a9f25`

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| haproxy | passed |
| big-data | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | failed |
| scaling | passed |
| scheduled-backup | passed |
| recreate | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| security-context | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/b38a9f258672c83457a9c87afc2b556498a2f2dc
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-b38a9f25`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| recreate | passed |
| storage | passed |
| restore-to-encrypted-cluster | passed |
| self-healing | passed |
| demand-backup | passed |
| self-healing-chaos | passed |
| pitr | passed |
| self-healing-advanced | passed |
| demand-backup-encrypted-with-tls | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| scaling | passed |
| big-data | passed |
| scheduled-backup | passed |
| haproxy | passed |
| operator-self-healing-chaos | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| security-context | passed |
| limits | passed |
| monitoring-2-0 | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1088/commits/b38a9f258672c83457a9c87afc2b556498a2f2dc
image: `perconalab/percona-xtradb-cluster-operator:PR-1088-b38a9f25`

**Review by egegunes — APPROVED** [review]

**Pull request merged**
