### PR TITLE
K8SPXC-554: improve object updates

### PR DESCRIPTION
**Pull request by qJkee**
[K8SPXC-554](https://jira.percona.com/browse/K8SPXC-554) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

Remove too frequent object updates

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| scheduled-backup | passed |
| big-data | passed |
| storage | passed |
| haproxy | failed |
| scaling | passed |
| upgrade-haproxy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| init-deploy | passed |
| self-healing-advanced | passed |
| demand-backup | passed |
| limits | passed |
| smart-update | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| upgrade-consistency | failed |
| proxysql-sidecar-res-limits | failed |
| users | failed |
| tls-issue-self | failed |
| pitr | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/876/commits/0c854c4c37b4525dc45694b18276e20202be2b8e
image: `perconalab/percona-xtradb-cluster-operator:PR-876-0c854c4c`

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| scaling | passed |
| haproxy | passed |
| big-data | passed |
| scheduled-backup | passed |
| recreate | passed |
| storage | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| demand-backup | passed |
| affinity | passed |
| operator-self-healing | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | failed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/876/commits/78cdd16ac0b193e8c66097100e9cb71559b04497
image: `perconalab/percona-xtradb-cluster-operator:PR-876-78cdd16a`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| storage | passed |
| big-data | passed |
| self-healing | passed |
| haproxy | passed |
| scaling | passed |
| self-healing-advanced | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| operator-self-healing | passed |
| limits | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| scheduled-backup | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/876/commits/78cdd16ac0b193e8c66097100e9cb71559b04497
image: `perconalab/percona-xtradb-cluster-operator:PR-876-78cdd16a`

**Review by delgod — APPROVED** [review]

**Comment by qJkee** [comment]
closed by #885

**Pull request closed without merging**
