### PR TITLE
Fix log messages when there are no old versions

### PR DESCRIPTION
**Pull request by blez**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| storage | passed |
| big-data | passed |
| init-deploy | failed |
| scaling | passed |
| self-healing | failed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | failed |
| self-healing-advanced | passed |
| limits | passed |
| demand-backup | passed |
| upgrade | passed |
| operator-self-healing | passed |
| monitoring | passed |
| upgrade-consistency | failed |
| security-context | passed |
| scheduled-backup | failed |
| monitoring-2-0 | passed |
| demand-backup-encrypted-with-tls | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |

**Comment by tplavcic** [comment]
Also this fix will be needed for PSMDB also. Thanks!

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| storage | passed |
| big-data | passed |
| scaling | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| self-healing | failed |
| limits | passed |
| restore-to-encrypted-cluster | failed |
| upgrade | passed |
| self-healing-advanced | failed |
| demand-backup | passed |
| monitoring | passed |
| upgrade-consistency | failed |
| operator-self-healing | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| scheduled-backup | failed |
| demand-backup-encrypted-with-tls | failed |
| one-pod | passed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | passed |
| users | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| scaling | passed |
| storage | passed |
| init-deploy | passed |
| recreate | passed |
| scaling-proxysql | passed |
| self-healing | failed |
| limits | passed |
| upgrade | passed |
| monitoring | failed |
| restore-to-encrypted-cluster | failed |
| self-healing-advanced | failed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| upgrade-consistency | failed |
| security-context | passed |
| affinity | passed |
| operator-self-healing | passed |
| one-pod | failed |
| auto-tuning | passed |
| scheduled-backup | failed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | failed |

**Pull request merged**
