### PR TITLE
K8SPXC-781: remove unused file

### PR DESCRIPTION
**Pull request by qJkee**
[K8SPXC-781](https://jira.percona.com/browse/K8SPXC-781) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

We do not use this code anymore

### CODE REVIEW

**Review by delgod — CHANGES_REQUESTED** [review]
should we also remove `genScheduleLabel` function?

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| big-data | passed |
| storage | passed |
| haproxy | passed |
| scheduled-backup | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| self-healing | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-chaos | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| self-healing-advanced | passed |
| one-pod | passed |
| auto-tuning | passed |
| self-healing-advanced-chaos | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| tls-issue-self | passed |
| upgrade-consistency | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/902/commits/c664514c4cebec6ea21e3e18ac2a8213430dc026
image: `perconalab/percona-xtradb-cluster-operator:PR-902-c664514c`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| recreate | passed |
| storage | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| self-healing-chaos | passed |
| demand-backup | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| pitr | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/902/commits/197cfa7701fa0dd398bcd930b357f2bb96e9d1eb
image: `perconalab/percona-xtradb-cluster-operator:PR-902-197cfa77`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| big-data | passed |
| upgrade-haproxy | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| init-deploy | passed |
| upgrade-proxysql | passed |
| limits | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/902/commits/197cfa7701fa0dd398bcd930b357f2bb96e9d1eb
image: `perconalab/percona-xtradb-cluster-operator:PR-902-197cfa77`

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| storage | passed |
| big-data | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| haproxy | passed |
| scaling | passed |
| scaling-proxysql | passed |
| operator-self-healing-chaos | passed |
| init-deploy | passed |
| limits | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/902/commits/197cfa7701fa0dd398bcd930b357f2bb96e9d1eb
image: `perconalab/percona-xtradb-cluster-operator:PR-902-197cfa77`

**Pull request merged**
