### PR TITLE
PMM-10724 Added v1-11-1 API version 

### PR DESCRIPTION
**Pull request by gen1us2k**
[PMM-10724](https://jira.percona.com/browse/PMM-10724) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

This fixes a bug in DBaaS UI when 1.11.1 is installed but PMM thinks that it's 1.11.0 because v1-11-1 does not exist

### CODE REVIEW

**Review by hors — CHANGES_REQUESTED** [review]
@gen1us2k please add task number 
also what about cw-bundle.yaml and cw-crd.yaml?
and also you need to change cr.yaml too

**Comment by gen1us2k** [comment]
@hors Added requested changes

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| We run 0 out of 35|

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1234/commits/6f074bb5ef7e107ee3f9ff04e909d601f76f826e
image: `perconalab/percona-xtradb-cluster-operator:PR-1234-v1.11.0-4-g6f074bb5`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| We run 0 out of 35|

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1234/commits/6f074bb5ef7e107ee3f9ff04e909d601f76f826e
image: `perconalab/percona-xtradb-cluster-operator:PR-1234-v1.11.0-4-g6f074bb5`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| We run 0 out of 35|

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1234/commits/93b639f3f632fe287ed8e88216f35901ee2c9fd6
image: `perconalab/percona-xtradb-cluster-operator:PR-1234-v1.11.0-5-g93b639f3`

**Review by egegunes — APPROVED** [review]
I think it's OK as a workaround. The CRD size grew too big so we need to `--server-side` when applying but it was already the case in the latest release.

just a heads up for the future @gen1us2k: We'll move to use `v1` as the default API version starting from next PXC release (in PSMDB we already moved to `v1`). Version checks using `kubectl api-versions` won't work after that change. We need to find a better way to detect operator version.

**Review by hors — APPROVED** [review]

**Pull request merged**
