### PR TITLE
K8SPXC-910 specify database name by default

### PR DESCRIPTION
**Pull request by delgod**
[K8SPXC-910](https://jira.percona.com/browse/K8SPXC-910) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| scaling | passed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| recreate | passed |
| haproxy | passed |
| big-data | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| demand-backup | passed |
| smart-update | passed |
| init-deploy | passed |
| limits | passed |
| pitr | passed |
| monitoring-2-0 | passed |
| upgrade-consistency | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| demand-backup-encrypted-with-tls | failed |
| proxysql-sidecar-res-limits | passed |
| users | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1065/commits/f074033579b3f7cad423c3fdac3f33c06e911be2
image: `perconalab/percona-xtradb-cluster-operator:PR-1065-f0740335`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| storage | passed |
| recreate | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| self-healing-chaos | failed |
| demand-backup | passed |
| pitr | passed |
| big-data | passed |
| demand-backup-encrypted-with-tls | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1065/commits/f074033579b3f7cad423c3fdac3f33c06e911be2
image: `perconalab/percona-xtradb-cluster-operator:PR-1065-f0740335`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| recreate | passed |
| scaling | passed |
| scheduled-backup | failed |
| upgrade-haproxy | passed |
| storage | passed |
| big-data | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1065/commits/f46b49ffe3ba7b63ca76f67f114d349321304513
image: `perconalab/percona-xtradb-cluster-operator:PR-1065-f46b49ff`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| scaling | passed |
| haproxy | passed |
| scaling-proxysql | passed |
| recreate | passed |
| init-deploy | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| pitr | passed |
| big-data | passed |
| scheduled-backup | failed |
| affinity | passed |
| demand-backup-encrypted-with-tls | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| storage | passed |
| tls-issue-self | passed |
| self-healing | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| self-healing-chaos | passed |
| validation-hook | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1065/commits/f46b49ffe3ba7b63ca76f67f114d349321304513
image: `perconalab/percona-xtradb-cluster-operator:PR-1065-f46b49ff`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| scheduled-backup | failed |
| recreate | passed |
| haproxy | passed |
| restore-to-encrypted-cluster | passed |
| init-deploy | passed |
| demand-backup | passed |
| limits | passed |
| pitr | passed |
| monitoring-2-0 | passed |
| demand-backup-encrypted-with-tls | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-haproxy | passed |
| storage | passed |
| scaling | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| self-healing-chaos | passed |
| security-context | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1065/commits/f46b49ffe3ba7b63ca76f67f114d349321304513
image: `perconalab/percona-xtradb-cluster-operator:PR-1065-f46b49ff`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| upgrade-haproxy | passed |
| operator-self-healing-chaos | passed |
| scaling | passed |
| recreate | passed |
| scaling-proxysql | passed |
| scheduled-backup | passed |
| big-data | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| demand-backup | passed |
| haproxy | passed |
| pitr | passed |
| init-deploy | passed |
| demand-backup-encrypted-with-tls | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1065/commits/f46b49ffe3ba7b63ca76f67f114d349321304513
image: `perconalab/percona-xtradb-cluster-operator:PR-1065-f46b49ff`

**Review by hors — APPROVED** [review]

**Review by defbin — APPROVED** [review]

**Pull request merged**
