### PR TITLE
K8SPXC-831: remove forceUnsafeBootstrap

### PR DESCRIPTION
**Pull request by defbin**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | failed |
| storage | failed |
| upgrade-haproxy | failed |
| haproxy | failed |
| big-data | failed |
| recreate | failed |
| scheduled-backup | failed |
| init-deploy | failed |
| scaling-proxysql | failed |
| restore-to-encrypted-cluster | failed |
| self-healing | failed |
| security-context | failed |
| demand-backup | failed |
| limits | failed |
| self-healing-chaos | failed |
| self-healing-advanced | failed |
| monitoring-2-0 | failed |
| pitr | failed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | failed |
| affinity | failed |
| demand-backup-encrypted-with-tls | failed |
| one-pod | failed |
| operator-self-healing-chaos | failed |
| upgrade-proxysql | failed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | failed |
| users | failed |
| tls-issue-self | failed |
| tls-issue-cert-manager | failed |
| tls-issue-cert-manager-ref | failed |
| smart-update | failed |
| validation-hook | passed |
| upgrade-consistency | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/989/commits/e230b88b3a5082cda8ec7b58c52986ac2cbb5d9c
image: `perconalab/percona-xtradb-cluster-operator:PR-989-e230b88b`

**Review by delgod — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | failed |
| scheduled-backup | failed |
| upgrade-haproxy | failed |
| storage | failed |
| recreate | failed |
| haproxy | failed |
| big-data | failed |
| init-deploy | failed |
| self-healing | failed |
| restore-to-encrypted-cluster | failed |
| scaling-proxysql | failed |
| demand-backup | failed |
| self-healing-chaos | failed |
| security-context | failed |
| limits | failed |
| self-healing-advanced | failed |
| monitoring-2-0 | failed |
| pitr | failed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | failed |
| affinity | failed |
| demand-backup-encrypted-with-tls | failed |
| operator-self-healing-chaos | failed |
| one-pod | failed |
| upgrade-proxysql | failed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | failed |
| users | failed |
| tls-issue-self | failed |
| tls-issue-cert-manager | failed |
| smart-update | failed |
| tls-issue-cert-manager-ref | failed |
| upgrade-consistency | failed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/989/commits/e230b88b3a5082cda8ec7b58c52986ac2cbb5d9c
image: `perconalab/percona-xtradb-cluster-operator:PR-989-e230b88b`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| recreate | passed |
| haproxy | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| big-data | passed |
| scheduled-backup | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | failed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-chaos | passed |
| demand-backup | passed |
| limits | passed |
| self-healing-advanced | passed |
| smart-update | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| self-healing-advanced-chaos | passed |
| one-pod | passed |
| auto-tuning | passed |
| pitr | passed |
| operator-self-healing | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| operator-self-healing-chaos | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/989/commits/1bd51e1890167129d5683b81b32ab508254e87e4
image: `perconalab/percona-xtradb-cluster-operator:PR-989-1bd51e18`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| recreate | passed |
| big-data | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| scaling | passed |
| scheduled-backup | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/989/commits/1bd51e1890167129d5683b81b32ab508254e87e4
image: `perconalab/percona-xtradb-cluster-operator:PR-989-1bd51e18`

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| scaling | passed |
| upgrade-haproxy | passed |
| storage | passed |
| scheduled-backup | passed |
| haproxy | passed |
| recreate | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| init-deploy | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-chaos | failed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| self-healing-advanced | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| operator-self-healing-chaos | failed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/989/commits/17fda233398011b655a8b47a819e73f592382dc2
image: `perconalab/percona-xtradb-cluster-operator:PR-989-17fda233`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| upgrade-haproxy | passed |
| scheduled-backup | failed |
| scaling | passed |
| big-data | passed |
| storage | passed |
| recreate | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| init-deploy | passed |
| self-healing-chaos | passed |
| demand-backup | passed |
| limits | passed |
| self-healing-advanced | passed |
| smart-update | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| self-healing-advanced-chaos | passed |
| one-pod | passed |
| auto-tuning | passed |
| pitr | passed |
| operator-self-healing | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| operator-self-healing-chaos | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/989/commits/06650978adbb6f6467877e0b457d4286156e06d2
image: `perconalab/percona-xtradb-cluster-operator:PR-989-06650978`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| haproxy | passed |
| operator-self-healing-chaos | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| recreate | passed |
| proxysql-sidecar-res-limits | passed |
| upgrade-haproxy | passed |
| restore-to-encrypted-cluster | passed |
| scaling | passed |
| users | passed |
| demand-backup | passed |
| scaling-proxysql | passed |
| tls-issue-self | passed |
| pitr | passed |
| security-context | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | passed |
| big-data | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| scheduled-backup | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/989/commits/06650978adbb6f6467877e0b457d4286156e06d2
image: `perconalab/percona-xtradb-cluster-operator:PR-989-06650978`

**Review by egegunes — APPROVED** [review]

**Review by nonemax — APPROVED** [review]

**Pull request merged**
