### PR TITLE
K8SPXC-896-897: check both SSL secret and SSL internal secret in reconsileSSL

### PR DESCRIPTION
**Pull request by srteam2020**
[K8SPXC-896](https://jira.percona.com/browse/K8SPXC-896) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

- Fixed K8SPXC-896
- Fixed K8SPXC-897

There is bug that prevents `ssl-internal` secret from getting created if operator crashs in the middle of reconcile.
Simpilfied reconcile logic is shown below,
```go
secretObj := corev1.Secret{}
err := r.client.Get(context.TODO(), ...) // Get ssl secret
if(notFoundSecret){
    r.client.Create(secretObj)  // (a)
    r.client.Create(secretInteralObj)  // (b)
}
```
Suppose if the operator crash after (a) but before (b). In that case, after the operator gets recovered the `secretObj` can be found, and the `secretInteralObj` will never be created.

This patch changes it to:
```go
secretObj := corev1.Secret{}
err := r.client.Get(context.TODO(), ...) // Get ssl secret
secretInternalObj := corev1.Secret{}
err := r.client.Get(context.TODO(), ...) // Get ssl internal secret
if(notFoundSecret || notFoundInternalSecret){
    r.client.Create(secretObj)  // (a)
    r.client.Create(secretInteralObj)  // (b)
}
```
which can fix the bug.

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| scaling | passed |
| big-data | passed |
| storage | failed |
| recreate | passed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| scaling-proxysql | failed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| smart-update | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| pitr | passed |
| security-context | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| upgrade-consistency | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| affinity | failed |
| demand-backup-encrypted-with-tls | passed |
| one-pod | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1043/commits/93df26af32ababa44421c675b41cbf0e66c0983d
image: `perconalab/percona-xtradb-cluster-operator:PR-1043-93df26af`

**Comment by srteam2020** [comment]
Is it possible to post the CI failure message? So that we can better debug the problem. It might be difficult for us to run the CI locally.

**Comment by egegunes** [comment]
CI failure was a generic error that says cluster is not ready in predefined duration. I ran one of the tests (monitoring-2-0) and saw the error:

```
failed to reconcile SSL.Please create your TLS secret some-name-ssl and monitoring-ssl-internal manually or setup cert-manager correctly: create ssl internally: create TLS secret: secrets "some-name-ssl" already exists
```

If the user provides `some-name-ssl` the operator still tries to create it because we do 

```
if (foundSecret && foundInternalSecret) {
  return
}

createCertificates()
```

We could ignore the `IsAlreadyExists` error from k8s. @hors what do you think?

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | failed |
| storage | failed |
| haproxy | failed |
| recreate | failed |
| scaling | failed |
| scheduled-backup | failed |
| upgrade-haproxy | failed |
| restore-to-encrypted-cluster | failed |
| init-deploy | failed |
| scaling-proxysql | failed |
| self-healing | passed |
| self-healing-chaos | failed |
| demand-backup | failed |
| limits | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| monitoring-2-0 | failed |
| security-context | failed |
| pitr | failed |
| affinity | failed |
| demand-backup-encrypted-with-tls | failed |
| upgrade-proxysql | failed |
| one-pod | passed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | failed |
| users | failed |
| tls-issue-self | failed |
| tls-issue-cert-manager | failed |
| tls-issue-cert-manager-ref | failed |
| smart-update | failed |
| validation-hook | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1043/commits/560e10561252a23e0135fbf7b9515f7719f2dd62
image: `perconalab/percona-xtradb-cluster-operator:PR-1043-560e1056`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | failed |
| storage | passed |
| big-data | passed |
| scaling | passed |
| recreate | passed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| init-deploy | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| demand-backup | passed |
| smart-update | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| pitr | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| upgrade-consistency | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1043/commits/acc1e19e98bcb7c7ef284eb692f3c940e1232f3e
image: `perconalab/percona-xtradb-cluster-operator:PR-1043-acc1e19e`

**Review by egegunes — DISMISSED** [review]

**Comment by srteam2020** [comment]
Hello, how is the status of this fix?

**Comment by egegunes** [comment]
@srteam2020 We discussed the issue with team. If SSL secrets exists, not creating SSL internal secret is intentional. The operator will use SSL secrets everywhere in this case. It seems it's not a bug.

**Comment by srteam2020** [comment]
Hello @egegunes Thanks for the reply!

We found that XtraDB can continue running even without the SSL internal certificate. However, this behavior can actually cause problems to the users -- We got confused by this problem and tried to debug this for days. Here are the reasons why we think this can actually cause problem and the checking logic should be improved:
1. As hinted both by the code (`createSSLManualy` always creates both secrets) and the docuementatin (https://www.percona.com/doc/kubernetes-operator-for-pxc/TLS.html), only creating one secret is an undesired behavior to us (unless this is explicitly specified by the user). We believe the current `createSSLManualy` is doing correctly by creating both secrets and what should be improved is the checking logic in `reconsileSSL`.
2. Using different certificates (secrets) for external/internal communications provides very strong security gaurantee and we really appreciate this feature. However, the imcomplete checking logic in `reconsileSSL` makes the operator unable to create the internal one which unnecessarily sacrifices the security, and this issue can be totally prevented by fixing the checking logic.

We enjoyed using the xtradb operator and really appreciate your awesome work on this! So we really hope we could help on improving the reliability and security of the operator and xtradb. This issue indeed causes much confusion and debugging work for us so we would really appreciate if the checking logic can be improved and two secretes are always created. So that no one will encounter the same issue in the future.

Please let us know your further concerns on the fix. We are willing to improve the PR.

**Comment by egegunes** [comment]
@srteam2020 same conversation in [PSMDB operator](https://github.com/percona/percona-server-mongodb-operator/pull/797#issuecomment-1009920742) applies here too

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| big-data | passed |
| scaling | passed |
| storage | passed |
| scheduled-backup | passed |
| recreate | passed |
| haproxy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| limits | passed |
| demand-backup | passed |
| smart-update | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| affinity | passed |
| one-pod | passed |
| pitr | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1043/commits/830a749e991675ab4c02778a01c4a5664dcd632c
image: `perconalab/percona-xtradb-cluster-operator:PR-1043-830a749e`

**Comment by srteam2020** [comment]
@egegunes I have updated the PR

**Review by delgod — APPROVED** [review]

**Review by egegunes — APPROVED** [review]

**Comment by egegunes** [comment]
@hors could you take a final look?

**Pull request merged**
