### PR TITLE
K8SPXC-554: improve object updates

### PR DESCRIPTION
**Pull request by qJkee**
[K8SPXC-554](https://jira.percona.com/browse/K8SPXC-554) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by delgod — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| haproxy | failed |
| upgrade-haproxy | passed |
| storage | passed |
| recreate | passed |
| scheduled-backup | passed |
| big-data | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| security-context | passed |
| init-deploy | failed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| operator-self-healing | passed |
| smart-update | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| demand-backup | passed |
| proxysql-sidecar-res-limits | failed |
| upgrade-consistency | failed |
| users | failed |
| pitr | failed |
| tls-issue-self | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/885/commits/a82532b0535fa66a0230de00a9cba4c145c91504
image: `perconalab/percona-xtradb-cluster-operator:PR-885-a82532b0`

**Review by egegunes — DISMISSED** [review]

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| big-data | passed |
| recreate | passed |
| storage | passed |
| haproxy | failed |
| scaling | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| scaling-proxysql | passed |
| upgrade-proxysql | passed |
| init-deploy | passed |
| security-context | passed |
| self-healing-advanced | passed |
| limits | passed |
| smart-update | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| demand-backup | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| upgrade-consistency | passed |
| pitr | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-cert-manager-ref | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/885/commits/8fdeef7c8ffe8e3dbc203168e678ee3e32576f92
image: `perconalab/percona-xtradb-cluster-operator:PR-885-8fdeef7c`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| big-data | passed |
| recreate | passed |
| scaling | passed |
| restore-to-encrypted-cluster | passed |
| scaling-proxysql | passed |
| demand-backup | passed |
| security-context | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| haproxy | failed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/885/commits/8fdeef7c8ffe8e3dbc203168e678ee3e32576f92
image: `perconalab/percona-xtradb-cluster-operator:PR-885-8fdeef7c`

**Review by delgod — APPROVED** [review]

**Review by egegunes — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| big-data | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| storage | passed |
| recreate | passed |
| scheduled-backup | passed |
| init-deploy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| operator-self-healing | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | failed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/885/commits/3bb4ecf377749ae639a71af0d24bad89939b2dac
image: `perconalab/percona-xtradb-cluster-operator:PR-885-3bb4ecf3`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| big-data | passed |
| scaling | passed |
| scaling-proxysql | passed |
| recreate | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| haproxy | passed |
| demand-backup-encrypted-with-tls | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| storage | passed |
| proxysql-sidecar-res-limits | passed |
| scheduled-backup | passed |
| self-healing | passed |
| users | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/885/commits/3bb4ecf377749ae639a71af0d24bad89939b2dac
image: `perconalab/percona-xtradb-cluster-operator:PR-885-3bb4ecf3`

**Pull request merged**
