### PR TITLE
K8SPXC-297: migrate to go modules

### PR DESCRIPTION
**Pull request by qJkee**
[K8SPXC-297](https://jira.percona.com/browse/K8SPXC-297)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| big-data | failed |
| recreate | passed |
| storage | failed |
| scaling-proxysql | failed |
| limits | passed |
| monitoring | passed |
| upgrade | passed |
| self-healing | failed |
| restore-to-encrypted-cluster | failed |
| demand-backup | failed |
| upgrade-consistency | passed |
| monitoring-2-0 | failed |
| self-healing-advanced | passed |
| security-context | passed |
| scheduled-backup | failed |
| affinity | passed |
| operator-self-healing | passed |
| one-pod | passed |
| demand-backup-encrypted-with-tls | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | failed |
| init-deploy | failed |
| big-data | failed |
| storage | passed |
| scaling | failed |
| scaling-proxysql | failed |
| limits | passed |
| upgrade | failed |
| self-healing | passed |
| upgrade-consistency | passed |
| monitoring | failed |
| restore-to-encrypted-cluster | failed |
| security-context | passed |
| monitoring-2-0 | failed |
| demand-backup | passed |
| affinity | passed |
| self-healing-advanced | failed |
| operator-self-healing | passed |
| one-pod | passed |
| auto-tuning | passed |
| scheduled-backup | failed |
| proxysql-sidecar-res-limits | passed |
| demand-backup-encrypted-with-tls | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| recreate | passed |
| init-deploy | passed |
| big-data | failed |
| scaling | passed |
| operator-self-healing | passed |
| limits | passed |
| monitoring | passed |
| restore-to-encrypted-cluster | failed |
| scaling-proxysql | passed |
| monitoring-2-0 | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| upgrade | passed |
| demand-backup | passed |
| scheduled-backup | failed |
| upgrade-consistency | passed |
| security-context | passed |
| demand-backup-encrypted-with-tls | failed |

**Comment by blez** [comment]
Please, add go.sum also

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| scaling | passed |
| init-deploy | passed |
| big-data | passed |
| recreate | passed |
| scaling-proxysql | passed |
| limits | passed |
| self-healing | passed |
| upgrade | passed |
| monitoring | failed |
| restore-to-encrypted-cluster | failed |
| demand-backup | failed |
| monitoring-2-0 | failed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| affinity | passed |
| security-context | passed |
| one-pod | passed |
| operator-self-healing | failed |
| auto-tuning | passed |
| scheduled-backup | failed |
| proxysql-sidecar-res-limits | passed |
| demand-backup-encrypted-with-tls | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| recreate | passed |
| restore-to-encrypted-cluster | failed |
| init-deploy | passed |
| limits | passed |
| monitoring | failed |
| scaling | passed |
| scaling-proxysql | passed |
| upgrade | passed |
| upgrade-consistency | passed |
| security-context | passed |
| monitoring-2-0 | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| demand-backup | failed |
| scheduled-backup | failed |
| demand-backup-encrypted-with-tls | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | failed |
| storage | passed |
| init-deploy | passed |
| scaling | passed |
| recreate | failed |
| restore-to-encrypted-cluster | failed |
| self-healing | failed |
| limits | passed |
| demand-backup | failed |
| scaling-proxysql | passed |
| monitoring | failed |
| self-healing-advanced | passed |
| scheduled-backup | failed |
| monitoring-2-0 | passed |
| demand-backup-encrypted-with-tls | failed |
| upgrade | passed |
| affinity | passed |
| operator-self-healing | passed |
| one-pod | passed |
| auto-tuning | passed |
| upgrade-consistency | passed |
| security-context | passed |
| proxysql-sidecar-res-limits | passed |

**Pull request merged**
