### PR TITLE
Improve smart-update limit logic

### PR DESCRIPTION
**Pull request by blez**
This PR fixes limit logic.
Previous implementation count timeout as 
```pseudocode
for i from 0 to waitLimit {
    sleep 1 second
    ok = doSomeWork...
    if ok {
       break
    }
}
```
There a 2 problems I see:
1. doSomeWork takes some time, but it does not counted as a time. So if time limit is 5 min this function will take `5 min` + `time to doSomeWork`*`count of iterations`
2. sleep 1 second. It's not proper to send request to PXC every second if previous call was unsuccessful.

In current implementation timeout is fair. In worst case it will take `waitLimit` + 10 sec

### CODE REVIEW

**Review by delgod — DISMISSED** [review]

**Review by dAdAbird — COMMENTED** [review]
Can you provide reasoning for these changes?
I am right that this is to reduce retries frequency? Is so, what impact does 1sec and how 10sec is better?

**Comment by blez** [comment]
@dAdAbird done

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| recreate | passed |
| storage | passed |
| scaling | passed |
| big-data | passed |
| init-deploy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| monitoring | passed |
| security-context | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| scheduled-backup | failed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |

**Comment by JNKPercona** [comment]
PXC operator docker - perconalab/percona-xtradb-cluster-operator:PR-577-744da188

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| haproxy | passed |
| operator-self-healing | passed |
| init-deploy | passed |
| limits | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| recreate | passed |
| scaling | passed |
| scaling-proxysql | passed |
| affinity | passed |
| restore-to-encrypted-cluster | passed |
| one-pod | passed |
| upgrade | passed |
| demand-backup | passed |
| auto-tuning | passed |
| upgrade-consistency | passed |
| scheduled-backup | passed |
| proxysql-sidecar-res-limits | passed |
| security-context | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | passed |

**Review by dAdAbird — COMMENTED** [review]
As for me `time.Timer` more relevant than the context here. Also, I don't like this tail 10 sec. On the other hand, using time.Ticker instead of Sleep would result in deferred first action...
So I propose to move retry logic to the separate func which has more ugly code to resolve described above problems but it isn't duplicated, so...
See my commit. 

Feel free to rework or revert it

**Comment by JNKPercona** [comment]
PXC operator docker - perconalab/percona-xtradb-cluster-operator:PR-577-033e7c82

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| storage | passed |
| scaling | passed |
| haproxy | passed |
| recreate | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring | passed |
| upgrade-consistency | passed |
| security-context | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

**Comment by blez** [comment]
@dAdAbird, it works, thanks
I just fix small bug here - https://github.com/percona/percona-xtradb-cluster-operator/pull/577/commits/51595a37fce78ce7bfc5740329f575d5f0d8a714

**Review by dAdAbird — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| storage | failed |
| big-data | passed |
| scaling | passed |
| recreate | passed |
| init-deploy | passed |
| scaling-proxysql | failed |
| limits | passed |
| restore-to-encrypted-cluster | passed |
| monitoring | failed |
| demand-backup | passed |
| self-healing | passed |
| upgrade | passed |
| scheduled-backup | passed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| security-context | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| demand-backup-encrypted-with-tls | passed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| scaling | passed |
| scaling-proxysql | failed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| big-data | passed |
| scheduled-backup | passed |
| demand-backup-encrypted-with-tls | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring | failed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| monitoring-2-0 | failed |
| upgrade | passed |
| upgrade-consistency | passed |
| security-context | passed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |

**Review by delgod — APPROVED** [review]

**Pull request merged**
