### PR TITLE
K8SPXC-573 escaped special symbols for 'XTRABACKUP_PASSWORD'

### PR DESCRIPTION
**Pull request by hors**
[K8SPXC-573](https://jira.percona.com/browse/K8SPXC-573) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | failed |
| haproxy | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| recreate | passed |
| storage | passed |
| init-deploy | passed |
| scaling-proxysql | failed |
| self-healing | passed |
| limits | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| monitoring-2-0 | passed |
| self-healing-advanced | passed |
| security-context | passed |
| affinity | passed |
| smart-update | passed |
| demand-backup | passed |
| one-pod | passed |
| operator-self-healing | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| pitr | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | failed |
| upgrade-consistency | passed |
| validation-hook | passed |
| scheduled-backup | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/810/commits/7caf67a1c8a39f37715f9d9a5e29a4ffa4506e1c
image: `perconalab/percona-xtradb-cluster-operator:PR-810-7caf67a1`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| haproxy | passed |
| recreate | passed |
| storage | passed |
| big-data | failed |
| upgrade-haproxy | passed |
| init-deploy | passed |
| self-healing | passed |
| scaling-proxysql | failed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | failed |
| affinity | passed |
| one-pod | passed |
| operator-self-healing | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | failed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| scheduled-backup | failed |
| security-context | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/810/commits/c6ed8d2b99e5eb539005f5b83cb18dc50be778e5
image: `perconalab/percona-xtradb-cluster-operator:PR-810-c6ed8d2b`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | failed |
| scaling | failed |
| upgrade-haproxy | failed |
| storage | failed |
| recreate | failed |
| haproxy | failed |
| init-deploy | failed |
| scaling-proxysql | failed |
| self-healing | passed |
| restore-to-encrypted-cluster | failed |
| security-context | passed |
| limits | passed |
| monitoring-2-0 | passed |
| self-healing-advanced | passed |
| affinity | passed |
| one-pod | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| scheduled-backup | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/810/commits/6b9ec9d0c4afeea8b3cee44d0e31276e553968d8
image: `perconalab/percona-xtradb-cluster-operator:PR-810-6b9ec9d0`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| storage | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| big-data | failed |
| haproxy | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| upgrade-proxysql | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| self-healing | passed |
| limits | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| demand-backup | passed |
| affinity | passed |
| one-pod | passed |
| self-healing-advanced | passed |
| auto-tuning | passed |
| operator-self-healing | failed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| scheduled-backup | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/810/commits/1c0926d650209de2718d33bc00a3c671602c44f9
image: `perconalab/percona-xtradb-cluster-operator:PR-810-1c0926d6`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/810/commits/1c0926d650209de2718d33bc00a3c671602c44f9
image: `perconalab/percona-xtradb-cluster-operator:PR-810-1c0926d6`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| haproxy | passed |
| scaling | passed |
| demand-backup | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| pitr | passed |
| limits | passed |
| upgrade-haproxy | passed |
| security-context | passed |
| demand-backup-encrypted-with-tls | passed |
| monitoring-2-0 | passed |
| scheduled-backup | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| storage | passed |
| proxysql-sidecar-res-limits | passed |
| self-healing | passed |
| users | passed |
| self-healing-advanced | passed |
| tls-issue-self | passed |
| operator-self-healing | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/810/commits/1c0926d650209de2718d33bc00a3c671602c44f9
image: `perconalab/percona-xtradb-cluster-operator:PR-810-1c0926d6`

**Pull request merged**
