### PR TITLE
K8SPXC-697 fix tabulation

### PR DESCRIPTION
**Pull request by delgod**
[K8SPXC-697](https://jira.percona.com/browse/K8SPXC-697) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by hors — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/eaa2df4b1ba09bfcdbd3ba7bbced45a5bdf3f0f0
image: `perconalab/percona-xtradb-cluster-operator:PR-827-eaa2df4b`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | failed |
| upgrade-haproxy | passed |
| scaling | passed |
| big-data | passed |
| recreate | passed |
| storage | passed |
| scaling-proxysql | passed |
| self-healing | failed |
| restore-to-encrypted-cluster | failed |
| security-context | passed |
| upgrade-proxysql | passed |
| init-deploy | passed |
| smart-update | failed |
| limits | passed |
| monitoring-2-0 | failed |
| self-healing-advanced | passed |
| demand-backup | failed |
| affinity | passed |
| one-pod | passed |
| operator-self-healing | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| upgrade-consistency | passed |
| users | failed |
| pitr | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/eaa2df4b1ba09bfcdbd3ba7bbced45a5bdf3f0f0
image: `perconalab/percona-xtradb-cluster-operator:PR-827-eaa2df4b`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| storage | passed |
| scaling-proxysql | passed |
| self-healing | failed |
| security-context | passed |
| big-data | passed |
| upgrade-haproxy | passed |
| recreate | passed |
| restore-to-encrypted-cluster | failed |
| haproxy | passed |
| upgrade-proxysql | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| demand-backup | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| upgrade-consistency | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| pitr | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/eaa2df4b1ba09bfcdbd3ba7bbced45a5bdf3f0f0
image: `perconalab/percona-xtradb-cluster-operator:PR-827-eaa2df4b`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| scaling | passed |
| big-data | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| scaling-proxysql | failed |
| self-healing | failed |
| init-deploy | passed |
| restore-to-encrypted-cluster | failed |
| upgrade-proxysql | passed |
| limits | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| self-healing-advanced | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| demand-backup | failed |
| users | passed |
| tls-issue-self | passed |
| operator-self-healing | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-consistency | passed |
| pitr | failed |
| demand-backup-encrypted-with-tls | failed |
| scheduled-backup | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/1e19729522c70e42863c8a200d31e6151af0da3e
image: `perconalab/percona-xtradb-cluster-operator:PR-827-1e197295`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | failed |
| big-data | passed |
| scaling | passed |
| scaling-proxysql | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| upgrade-haproxy | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| storage | passed |
| self-healing | failed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| security-context | passed |
| self-healing-advanced | passed |
| demand-backup | failed |
| operator-self-healing | passed |
| pitr | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/1e19729522c70e42863c8a200d31e6151af0da3e
image: `perconalab/percona-xtradb-cluster-operator:PR-827-1e197295`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | failed |
| storage | failed |
| recreate | failed |
| upgrade-haproxy | failed |
| big-data | failed |
| scaling | failed |
| init-deploy | failed |
| self-healing | failed |
| restore-to-encrypted-cluster | failed |
| scaling-proxysql | failed |
| upgrade-proxysql | failed |
| limits | failed |
| demand-backup | failed |
| self-healing-advanced | failed |
| security-context | failed |
| smart-update | failed |
| monitoring-2-0 | failed |
| pitr | failed |
| operator-self-healing | failed |
| upgrade-consistency | failed |
| affinity | failed |
| demand-backup-encrypted-with-tls | failed |
| scheduled-backup | failed |
| one-pod | failed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | failed |
| users | failed |
| tls-issue-self | failed |
| tls-issue-cert-manager | failed |
| tls-issue-cert-manager-ref | failed |
| validation-hook | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/cb3f907ed7747e56e27380fdf0a93c34d66edd16
image: `perconalab/percona-xtradb-cluster-operator:PR-827-cb3f907e`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| haproxy | passed |
| big-data | passed |
| recreate | passed |
| storage | passed |
| scaling | passed |
| self-healing | failed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | failed |
| upgrade-proxysql | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| self-healing-advanced | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| operator-self-healing | passed |
| demand-backup | failed |
| proxysql-sidecar-res-limits | passed |
| security-context | passed |
| users | failed |
| pitr | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| demand-backup-encrypted-with-tls | failed |
| scheduled-backup | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/cb3f907ed7747e56e27380fdf0a93c34d66edd16
image: `perconalab/percona-xtradb-cluster-operator:PR-827-cb3f907e`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| storage | passed |
| haproxy | passed |
| scaling-proxysql | failed |
| init-deploy | passed |
| self-healing | failed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| self-healing-advanced | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| operator-self-healing | passed |
| security-context | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/a5b62671c32412729f0255bfebc070d708e3145a
image: `perconalab/percona-xtradb-cluster-operator:PR-827-a5b62671`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | failed |
| upgrade-haproxy | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| recreate | passed |
| restore-to-encrypted-cluster | failed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| demand-backup | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/cb3f907ed7747e56e27380fdf0a93c34d66edd16
image: `perconalab/percona-xtradb-cluster-operator:PR-827-cb3f907e`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| storage | passed |
| self-healing | failed |
| upgrade-haproxy | passed |
| haproxy | passed |
| init-deploy | passed |
| recreate | passed |
| limits | passed |
| restore-to-encrypted-cluster | failed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| big-data | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| demand-backup | failed |
| pitr | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/cb3f907ed7747e56e27380fdf0a93c34d66edd16
image: `perconalab/percona-xtradb-cluster-operator:PR-827-cb3f907e`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/768f4c448a5897c78e7fd93855730325348acec1
image: `perconalab/percona-xtradb-cluster-operator:PR-827-768f4c44`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| recreate | failed |
| storage | failed |
| scaling | failed |
| big-data | passed |
| haproxy | passed |
| init-deploy | passed |
| upgrade-proxysql | passed |
| limits | passed |
| monitoring-2-0 | failed |
| smart-update | passed |
| scaling-proxysql | failed |
| restore-to-encrypted-cluster | failed |
| self-healing | failed |
| affinity | passed |
| upgrade-consistency | passed |
| security-context | passed |
| demand-backup | failed |
| self-healing-advanced | failed |
| one-pod | passed |
| auto-tuning | failed |
| operator-self-healing | failed |
| proxysql-sidecar-res-limits | failed |
| pitr | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/c8f5636f232ec9ee1f2bf727613173d13a6d1cd9
image: `perconalab/percona-xtradb-cluster-operator:PR-827-c8f5636f`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | failed |
| upgrade-haproxy | passed |
| recreate | failed |
| big-data | passed |
| storage | failed |
| haproxy | passed |
| init-deploy | passed |
| upgrade-proxysql | passed |
| limits | passed |
| monitoring-2-0 | failed |
| smart-update | passed |
| scaling-proxysql | failed |
| self-healing | failed |
| restore-to-encrypted-cluster | failed |
| affinity | passed |
| one-pod | passed |
| security-context | passed |
| self-healing-advanced | failed |
| demand-backup | failed |
| auto-tuning | failed |
| upgrade-consistency | passed |
| operator-self-healing | failed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| pitr | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/77a497f49ea4e4ce4d875565cc3703c94769d46b
image: `perconalab/percona-xtradb-cluster-operator:PR-827-77a497f4`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/768f4c448a5897c78e7fd93855730325348acec1
image: `perconalab/percona-xtradb-cluster-operator:PR-827-768f4c44`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/9e418f2cb4b50e253454b5bf174bdfd7a6028edb
image: `perconalab/percona-xtradb-cluster-operator:PR-827-9e418f2c`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/9e418f2cb4b50e253454b5bf174bdfd7a6028edb
image: `perconalab/percona-xtradb-cluster-operator:PR-827-9e418f2c`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/57f6e5df1ebacc9544e8ac2c9f0ff4d5acc66bc1
image: `perconalab/percona-xtradb-cluster-operator:PR-827-57f6e5df`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/baed2e8e2930fe503cf2a6f7cca880d3c0b464dd
image: `perconalab/percona-xtradb-cluster-operator:PR-827-baed2e8e`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/3c4cbd446942b9f292e4ef26df8c36b4ed5bdef3
image: `perconalab/percona-xtradb-cluster-operator:PR-827-3c4cbd44`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/3c4cbd446942b9f292e4ef26df8c36b4ed5bdef3
image: `perconalab/percona-xtradb-cluster-operator:PR-827-3c4cbd44`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| upgrade-haproxy | passed |
| storage | passed |
| recreate | passed |
| scaling | passed |
| big-data | passed |
| scheduled-backup | failed |
| init-deploy | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | failed |
| scaling-proxysql | passed |
| upgrade-proxysql | passed |
| limits | passed |
| security-context | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| one-pod | passed |
| operator-self-healing | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | failed |
| demand-backup | failed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| pitr | passed |
| upgrade-consistency | failed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/dc63b47315514de8fdeb3a5b07ebea164aeb2d5e
image: `perconalab/percona-xtradb-cluster-operator:PR-827-dc63b473`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/dc63b47315514de8fdeb3a5b07ebea164aeb2d5e
image: `perconalab/percona-xtradb-cluster-operator:PR-827-dc63b473`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| recreate | passed |
| restore-to-encrypted-cluster | failed |
| big-data | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| storage | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| affinity | passed |
| self-healing-advanced | passed |
| security-context | passed |
| one-pod | passed |
| operator-self-healing | passed |
| auto-tuning | passed |
| scheduled-backup | passed |
| proxysql-sidecar-res-limits | passed |
| upgrade-proxysql | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| demand-backup | failed |
| pitr | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/dc63b47315514de8fdeb3a5b07ebea164aeb2d5e
image: `perconalab/percona-xtradb-cluster-operator:PR-827-dc63b473`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| upgrade-haproxy | passed |
| recreate | passed |
| haproxy | passed |
| big-data | passed |
| scheduled-backup | passed |
| scaling | passed |
| init-deploy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| operator-self-healing | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/827/commits/5c132a766ae2805802c1f0cb78f9b998f606c758
image: `perconalab/percona-xtradb-cluster-operator:PR-827-5c132a76`

**Review by hors — APPROVED** [review]

**Pull request merged**
