### PR TITLE
K8SPXC-256 fix "no such file issue"

### PR DESCRIPTION
**Pull request by delgod**
[K8SPXC-257](https://jira.percona.com/browse/K8SPXC-257)

init container runs not in all cases, see https://github.com/kubernetes/kubernetes/issues/66699
in result, after SST, we sometimes have the issue:
```
Error: failed to start container "pxc": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/var/lib/mysql/pxc-entrypoint.sh\": stat /var/lib/mysql/pxc-entrypoint.sh: no such file or directory": unknown
```

joiner during SST runs this line https://github.com/percona/percona-xtradb-cluster/blob/8.0/scripts/wsrep_sst_xtrabackup-v2.sh#L2040
in result `/var/lib/mysql/pxc-entrypoint.sh` file become deleted
but after some things, like failed liveness probe, Kubernetes restart Pod without Init container which should copy `/var/lib/mysql/pxc-entrypoint.sh` file back

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | failed |
| storage | failed |
| init-deploy | failed |
| scaling | failed |
| big-data | failed |
| self-healing | failed |
| restore-to-encrypted-cluster | failed |
| scaling-proxysql | failed |
| limits | failed |
| self-healing-advanced | failed |
| monitoring | failed |
| upgrade | failed |
| demand-backup | failed |
| operator-self-healing | failed |
| upgrade-consistency | passed |
| scheduled-backup | failed |
| security-context | failed |
| monitoring-2-0 | failed |
| demand-backup-encrypted-with-tls | failed |
| affinity | failed |
| one-pod | failed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| scaling | failed |
| init-deploy | failed |
| recreate | failed |
| big-data | failed |
| self-healing | failed |
| scaling-proxysql | failed |
| restore-to-encrypted-cluster | failed |
| limits | failed |
| self-healing-advanced | failed |
| upgrade | failed |
| monitoring | failed |
| demand-backup | failed |
| scheduled-backup | failed |
| operator-self-healing | failed |
| demand-backup-encrypted-with-tls | failed |
| monitoring-2-0 | failed |
| affinity | failed |
| one-pod | failed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | failed |
| upgrade-consistency | passed |
| security-context | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | failed |
| init-deploy | failed |
| storage | failed |
| scaling | failed |
| recreate | failed |
| self-healing | failed |
| scaling-proxysql | failed |
| restore-to-encrypted-cluster | failed |
| limits | passed |
| self-healing-advanced | failed |
| upgrade | passed |
| demand-backup | failed |
| monitoring | failed |
| upgrade-consistency | passed |
| operator-self-healing | failed |
| scheduled-backup | failed |
| security-context | failed |
| monitoring-2-0 | failed |
| demand-backup-encrypted-with-tls | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| big-data | passed |
| recreate | passed |
| init-deploy | failed |
| storage | passed |
| self-healing | failed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | failed |
| limits | passed |
| self-healing-advanced | failed |
| monitoring | passed |
| demand-backup | passed |
| operator-self-healing | failed |
| monitoring-2-0 | passed |
| scheduled-backup | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| demand-backup-encrypted-with-tls | failed |
| upgrade-consistency | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| upgrade | passed |
| big-data | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| storage | passed |
| self-healing | failed |
| init-deploy | failed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| security-context | failed |
| limits | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| operator-self-healing | passed |
| demand-backup-encrypted-with-tls | passed |

**Comment by delgod** [comment]
> I'm trying to check image `perconalab/percona-xtradb-cluster-operator:k8spxc-257-fix-no-such-file` but I'm bumping into following issue:

it was outdated, I have prepared new version - `perconalab/percona-xtradb-cluster-operator:k8spxc-257-fix-no-such-file`

**Pull request merged**
