### PR TITLE
K8SPXC-510 ENV variables for offline operator

### PR DESCRIPTION
**Pull request by cap1984**
[K8SPXC-510](https://jira.percona.com/browse/K8SPXC-510)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | failed |
| haproxy | passed |
| big-data | passed |
| storage | passed |
| scaling | passed |
| recreate | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| security-context | passed |
| init-deploy | passed |
| self-healing-advanced | passed |
| restore-to-encrypted-cluster | passed |
| limits | failed |
| operator-self-healing | failed |
| demand-backup | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | failed |
| auto-tuning | passed |
| scheduled-backup | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | failed |
| smart-update | failed |
| upgrade-consistency | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| upgrade-haproxy | failed |
| big-data | passed |
| storage | passed |
| recreate | passed |
| scaling | passed |
| init-deploy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| upgrade-proxysql | failed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| limits | failed |
| self-healing-advanced | passed |
| smart-update | failed |
| operator-self-healing | failed |
| demand-backup | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | failed |
| auto-tuning | passed |
| scheduled-backup | passed |
| upgrade-consistency | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-haproxy | failed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | failed |
| big-data | passed |
| haproxy | passed |
| init-deploy | passed |
| scaling | passed |
| limits | failed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-proxysql | failed |
| monitoring | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| smart-update | failed |
| upgrade-consistency | passed |

**Review by tplavcic — APPROVED** [review]

**Review by delgod — CHANGES_REQUESTED** [review]
I belive we should rollback the previous ENV changes the first

**Review by delgod — APPROVED** [review]

**Pull request merged**
