### PR TITLE
K8SPXC-485 Add test for logcollector

### PR DESCRIPTION
**Pull request by hors**
[K8SPXC-485](https://jira.percona.com/browse/K8SPXC-485)

K8SPXC-531 - fix operator-self-healing test

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | failed |
| haproxy | passed |
| scaling | passed |
| big-data | passed |
| upgrade-haproxy | failed |
| storage | passed |
| self-healing | failed |
| scaling-proxysql | passed |
| init-deploy | passed |
| upgrade-proxysql | failed |
| limits | failed |
| security-context | passed |
| smart-update | passed |
| restore-to-encrypted-cluster | passed |
| self-healing-advanced | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| operator-self-healing | failed |
| demand-backup | passed |
| affinity | passed |
| one-pod | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| upgrade-consistency | failed |
| users | failed |
| scheduled-backup | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| demand-backup-encrypted-with-tls | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| recreate | passed |
| upgrade-haproxy | failed |
| storage | passed |
| big-data | passed |
| haproxy | passed |
| init-deploy | passed |
| self-healing | failed |
| scaling-proxysql | passed |
| upgrade-proxysql | failed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| limits | failed |
| smart-update | passed |
| demand-backup | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| self-healing-advanced | passed |
| affinity | passed |
| one-pod | failed |
| operator-self-healing | failed |
| auto-tuning | passed |
| scheduled-backup | passed |
| upgrade-consistency | failed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| storage | passed |
| recreate | passed |
| upgrade-haproxy | failed |
| scaling | passed |
| big-data | passed |
| init-deploy | passed |
| self-healing | failed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | failed |
| security-context | passed |
| limits | failed |
| smart-update | passed |
| demand-backup | passed |
| monitoring | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| operator-self-healing | failed |
| affinity | passed |
| one-pod | failed |
| scheduled-backup | failed |
| auto-tuning | passed |
| upgrade-consistency | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| demand-backup-encrypted-with-tls | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| upgrade-haproxy | failed |
| storage | passed |
| haproxy | passed |
| big-data | passed |
| recreate | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| self-healing | failed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | failed |
| limits | failed |
| smart-update | passed |
| demand-backup | passed |
| monitoring | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | failed |
| auto-tuning | passed |
| scheduled-backup | passed |
| upgrade-consistency | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| big-data | passed |
| recreate | passed |
| upgrade-haproxy | failed |
| scaling | passed |
| haproxy | passed |
| self-healing | failed |
| scaling-proxysql | passed |
| init-deploy | passed |
| upgrade-proxysql | failed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| limits | failed |
| smart-update | passed |
| demand-backup | passed |
| self-healing-advanced | passed |
| monitoring | passed |
| operator-self-healing | failed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| upgrade-consistency | passed |
| users | passed |
| scheduled-backup | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| demand-backup-encrypted-with-tls | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| big-data | passed |
| recreate | passed |
| haproxy | passed |
| scaling | passed |
| upgrade-haproxy | failed |
| self-healing | failed |
| init-deploy | passed |
| scaling-proxysql | passed |
| upgrade-proxysql | failed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| limits | failed |
| smart-update | passed |
| demand-backup | passed |
| monitoring | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | failed |
| auto-tuning | passed |
| operator-self-healing | failed |
| proxysql-sidecar-res-limits | passed |
| upgrade-consistency | passed |
| users | passed |
| scheduled-backup | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| demand-backup-encrypted-with-tls | failed |

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| scaling | passed |
| restore-to-encrypted-cluster | passed |
| scaling-proxysql | passed |
| haproxy | passed |
| upgrade-haproxy | failed |
| big-data | passed |
| security-context | passed |
| demand-backup | passed |
| init-deploy | passed |
| storage | passed |
| scheduled-backup | passed |
| limits | failed |
| self-healing | failed |
| upgrade-proxysql | failed |
| monitoring | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| operator-self-healing | failed |
| demand-backup-encrypted-with-tls | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| haproxy | passed |
| big-data | passed |
| upgrade-haproxy | failed |
| recreate | passed |
| storage | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| security-context | passed |
| self-healing | failed |
| upgrade-proxysql | failed |
| restore-to-encrypted-cluster | passed |
| limits | failed |
| smart-update | passed |
| demand-backup | passed |
| monitoring | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| operator-self-healing | failed |
| affinity | passed |
| one-pod | failed |
| auto-tuning | passed |
| scheduled-backup | passed |
| upgrade-consistency | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

**Review by cap1984 — APPROVED** [review]

**Pull request merged**
