### PR TITLE
CLOUD-622 add examples of architecture decision records

### PR DESCRIPTION
**Pull request by hors**
[CLOUD-622](https://jira.percona.com/browse/CLOUD-622) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| haproxy | passed |
| scaling | passed |
| storage | passed |
| recreate | passed |
| scheduled-backup | passed |
| big-data | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| init-deploy | passed |
| self-healing-advanced | passed |
| limits | passed |
| demand-backup | passed |
| smart-update | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | failed |
| upgrade-consistency | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/868/commits/fe770806569dcd658e7875d5d1014dac0247afce
image: `perconalab/percona-xtradb-cluster-operator:PR-868-fe770806`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| haproxy | passed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| storage | passed |
| big-data | passed |
| scaling | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| security-context | passed |
| self-healing-advanced | passed |
| init-deploy | passed |
| demand-backup | passed |
| smart-update | passed |
| limits | passed |
| operator-self-healing | failed |
| monitoring-2-0 | failed |
| affinity | passed |
| pitr | passed |
| one-pod | passed |
| auto-tuning | passed |
| upgrade-consistency | passed |
| proxysql-sidecar-res-limits | passed |
| demand-backup-encrypted-with-tls | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/868/commits/2af499fa58c1830d4e34109f0c8a35a560e57636
image: `perconalab/percona-xtradb-cluster-operator:PR-868-2af499fa`

**Review by delgod — DISMISSED** [review]

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| scaling | passed |
| storage | passed |
| haproxy | passed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| big-data | passed |
| self-healing | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | failed |
| demand-backup | passed |
| smart-update | passed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/868/commits/51252c3689036c23c7a91c96c12c75acfbe31760
image: `perconalab/percona-xtradb-cluster-operator:PR-868-51252c36`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| big-data | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | failed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/868/commits/51252c3689036c23c7a91c96c12c75acfbe31760
image: `perconalab/percona-xtradb-cluster-operator:PR-868-51252c36`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| big-data | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| storage | passed |
| self-healing | passed |
| recreate | passed |
| self-healing-advanced | passed |
| restore-to-encrypted-cluster | passed |
| haproxy | passed |
| operator-self-healing | passed |
| demand-backup | passed |
| init-deploy | passed |
| pitr | passed |
| limits | passed |
| demand-backup-encrypted-with-tls | passed |
| monitoring-2-0 | failed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/868/commits/51252c3689036c23c7a91c96c12c75acfbe31760
image: `perconalab/percona-xtradb-cluster-operator:PR-868-51252c36`

**Pull request merged**
