### PR TITLE
K8SPXC-683 Add check for backupName and backuoSource fields simultane…

### PR DESCRIPTION
**Pull request by nonemax**
[K8SPXC-683](https://jira.percona.com/browse/K8SPXC-683) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

…ous setting

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| big-data | passed |
| upgrade-haproxy | passed |
| recreate | passed |
| haproxy | passed |
| storage | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| self-healing | passed |
| upgrade-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| smart-update | failed |
| demand-backup | passed |
| affinity | passed |
| operator-self-healing | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | failed |
| users | passed |
| security-context | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/822/commits/0d5786329d192018aece0b3baa7f1d4ac7f157bb
image: `perconalab/percona-xtradb-cluster-operator:PR-822-0d578632`

**Review by blez — APPROVED** [review]

**Review by tplavcic — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| storage | passed |
| haproxy | passed |
| self-healing | passed |
| init-deploy | passed |
| self-healing-advanced | passed |
| limits | passed |
| operator-self-healing | passed |
| monitoring-2-0 | passed |
| big-data | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| tls-issue-self | passed |
| restore-to-encrypted-cluster | passed |
| tls-issue-cert-manager | passed |
| demand-backup | passed |
| tls-issue-cert-manager-ref | passed |
| pitr | failed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/822/commits/0d5786329d192018aece0b3baa7f1d4ac7f157bb
image: `perconalab/percona-xtradb-cluster-operator:PR-822-0d578632`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| big-data | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| storage | passed |
| upgrade-haproxy | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/822/commits/0d5786329d192018aece0b3baa7f1d4ac7f157bb
image: `perconalab/percona-xtradb-cluster-operator:PR-822-0d578632`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| haproxy | passed |
| upgrade-haproxy | passed |
| pitr | failed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| storage | passed |
| one-pod | passed |
| self-healing | passed |
| scaling | passed |
| self-healing-advanced | passed |
| auto-tuning | passed |
| scaling-proxysql | passed |
| operator-self-healing | passed |
| proxysql-sidecar-res-limits | passed |
| security-context | passed |
| users | passed |
| tls-issue-self | passed |
| big-data | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/822/commits/0d5786329d192018aece0b3baa7f1d4ac7f157bb
image: `perconalab/percona-xtradb-cluster-operator:PR-822-0d578632`

**Pull request merged**
