### PR TITLE
Use hostname instead of IP

### PR DESCRIPTION
**Pull request by laimison**
This is an improvement in `wsrep_cluster_address` to ensure hostnames instead of IPs.

PLEASE NOTE: it requires `yum install -y bind-utils` in a `Dockerfile`, in case you think PR is useful for merge

Motivation:

* Kubernetes can change pod IP (e.g. in the event of network drop when Calico or other tunnel is reinitialised, pod deletion, etc.). So I thought it's good idea to avoid reaching this line https://github.com/percona/percona-xtradb-cluster-operator/blob/main/build/pxc-configure-pxc.sh#L55

* At the moment, it already prefers hostnames collected via `mysql` command https://github.com/percona/percona-xtradb-cluster-operator/blob/main/build/pxc-configure-pxc.sh#L50 , but I've got some edge case, I'll explain

----

I've worked on migration to another cluster and somehow my operator's secret was incorrect (maybe used some weird special character, accidentally changed it or just incorrect password used so this is about human failure)

New cluster successfully started from backup and I was using it for some days without noticing an issue:

```
$ ~/Documents/git $ k logs -n mm-p mattermost-cluster-pxc-2 pxc | grep -B 3 ERROR
++ mysql_root_exec 10.233.76.59 'select @@hostname'
++ local server=10.233.76.59
++ local 'query=select @@hostname'
ERROR 1045 (28000): Access denied for user 'operator'@'10.233.100.252' (using password: YES)
```

gcomm connectors were:

```
k exec -it mattermost-cluster-pxc-0 -n mm-p -c pxc -- grep wsrep_cluster_address /etc/mysql/node.cnf
wsrep_cluster_address=gcomm://

k exec -it mattermost-cluster-pxc-1 -n mm-p -c pxc -- grep wsrep_cluster_address /etc/mysql/node.cnf
wsrep_cluster_address=gcomm://10.233.76.59

k exec -it mattermost-cluster-pxc-2 -n mm-p -c pxc -- grep wsrep_cluster_address /etc/mysql/node.cnf
wsrep_cluster_address=gcomm://10.233.76.59,10.233.86.125
```

So I understand why it placed IPs (where personally I would prefer hostnames, because IPs are not guaranteed in Kubernetes)

In addition, I've tried to drain one node for the test and had some issue with it until pod came back online. Maybe because of these `wsrep_cluster_address` values.

Anyway, I don't have any issue to register as I'm aware how to get hostnames by fixing operator's password and restarting instances. So cluster is working well now, but I believe this PR could be useful to help others to not face this edge case or at least improve the situation.

The PR focus is better handling of hostnames/improving situation of using `svc` DNSes, in general.

Please let me know what are your plans.

Many thanks!

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| big-data | passed |
| haproxy | passed |
| recreate | passed |
| scaling | passed |
| storage | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| security-context | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| affinity | passed |
| one-pod | passed |
| operator-self-healing | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | failed |
| demand-backup-encrypted-with-tls | passed |
| scheduled-backup | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/811/commits/d3dc186a155481b0230b174071ea39eb6a4e7c2b
image: `perconalab/percona-xtradb-cluster-operator:PR-811-d3dc186a`

**Comment by delgod** [comment]
Hi @laimison,

Yes, we thought about it many times, it absolutely sounds like the right design/idea, and as usual, there is a "But" 😞.
We saw some amount of "strange" issues and timeouts with Percona XtraDB Cluster(not Kubernetes) when something went wrong in situations like restarts, crash, crash recovery, networking issues, split-brain, etc.
We decided that it is better to avoid communications with the newly started pod until it is fully ready to join the cluster.
Using IPs allows us to reach this goal.

Hope for your understanding.

**Comment by laimison** [comment]
> Hi @laimison,
> 
> Yes, we thought about it many times, it absolutely sounds like the right design/idea, and as usual, there is a "But" 😞.
> We saw some amount of "strange" issues and timeouts with Percona XtraDB Cluster(not Kubernetes) when something went wrong in situations like restarts, crash, crash recovery, networking issues, split-brain, etc.
> We decided that it is better to avoid communications with the newly started pod until it is fully ready to join the cluster.
> Using IPs allows us to reach this goal.
> 
> Hope for your understanding.

Absolutely, makes sense. I didn't expect this to be merged, most likely. That's too simple to be placed, hehe.

I was more interested to learn out this situation, checked the code and it helped to solve my own (human failure) issue. 
Now cluster is working perfectly and survives random restarts/network drops in my environment based on tests.

I was also thinking about validation whether operator's password is correct. For instance add error handling here https://github.com/percona/percona-xtradb-cluster-operator/blob/main/build/pxc-configure-pxc.sh#L36 if received `ERROR 1045 (28000): Access denied for user`, do `exit 1` and don't allow startup. But that has few caveats:
1) Access denied error is very wide https://www.percona.com/blog/2019/07/05/fixing-a-mysql-1045-error/
2) Operator should be programmed to solve issues on his own so exiting everything is very drastic solution nowadays
3) Better to validate password on same instance, instead of checking cluster members and depending on them, but if I'm right DB is only started here https://github.com/percona/percona-xtradb-cluster-operator/blob/main/build/pxc-entrypoint.sh#L547 so not right way to fork and do actions after it's online

Anyway, thanks for review. Please just close this one and I will correct another PR for merge, as discussed.

**Comment by delgod** [comment]
about password validation
can you please create a jira ticket with an example of secrets which doesn't work?
we solved a similar issue - https://jira.percona.com/browse/K8SPXC-573

**Pull request closed without merging**
