### PR TITLE
K8SPXC-542: add cluster hash prefix to backup job name

### PR DESCRIPTION
**Pull request by qJkee**
[K8SPXC-542](https://jira.percona.com/browse/K8SPXC-542) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

This pr solves a problem when we have different clusters but with the same backup jobs.
Now, we add a hash from cluster name and add it as a prefix to cron job name.
User will manage backup names in the old name, changes will be seen only when typing `kubectl get cronjobs.batch`

Old backup cron jobs will be deleted and new one(with the new names) created automatically.

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| upgrade-haproxy | passed |
| recreate | passed |
| haproxy | passed |
| big-data | passed |
| scaling | passed |
| init-deploy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| security-context | failed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | failed |
| smart-update | passed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| demand-backup | passed |
| proxysql-sidecar-res-limits | failed |
| upgrade-consistency | passed |
| users | failed |
| tls-issue-self | passed |
| pitr | failed |
| tls-issue-cert-manager | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| haproxy | passed |
| restore-to-encrypted-cluster | passed |
| init-deploy | passed |
| demand-backup | passed |
| limits | passed |
| pitr | passed |
| monitoring-2-0 | passed |
| big-data | passed |
| storage | passed |
| scaling | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| self-healing-advanced | passed |
| security-context | failed |
| operator-self-healing | passed |
| upgrade-haproxy | passed |
| upgrade-proxysql | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| users | failed |
| demand-backup-encrypted-with-tls | passed |
| scheduled-backup | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

**Review by delgod — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| scaling | passed |
| recreate | passed |
| storage | passed |
| haproxy | passed |
| big-data | passed |
| init-deploy | passed |
| self-healing | passed |
| upgrade-proxysql | passed |
| limits | passed |
| scaling-proxysql | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| security-context | failed |
| restore-to-encrypted-cluster | passed |
| smart-update | passed |
| affinity | passed |
| one-pod | passed |
| demand-backup | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| operator-self-healing | passed |
| users | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | failed |
| big-data | passed |
| haproxy | passed |
| recreate | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| storage | passed |
| tls-issue-self | passed |
| upgrade-haproxy | passed |
| self-healing | passed |
| tls-issue-cert-manager | passed |
| self-healing-advanced | passed |
| tls-issue-cert-manager-ref | passed |
| operator-self-healing | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| scheduled-backup | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| upgrade-haproxy | passed |
| storage | passed |
| recreate | passed |
| big-data | passed |
| haproxy | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| self-healing | failed |
| security-context | failed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| monitoring-2-0 | passed |
| smart-update | failed |
| demand-backup | passed |
| affinity | passed |
| self-healing-advanced | passed |
| one-pod | passed |
| auto-tuning | passed |
| operator-self-healing | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-consistency | passed |

**Review by blez — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| big-data | passed |
| demand-backup | passed |
| pitr | passed |
| scaling | passed |
| demand-backup-encrypted-with-tls | passed |
| scaling-proxysql | passed |
| security-context | failed |
| haproxy | passed |
| upgrade-haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| upgrade-consistency | passed |

**Review by hors — CHANGES_REQUESTED** [review]
@qJkee  please fix security-context test

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| big-data | passed |
| storage | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| scaling | passed |
| init-deploy | passed |
| self-healing | failed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| self-healing-advanced | passed |
| one-pod | passed |
| auto-tuning | passed |
| operator-self-healing | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup | passed |
| upgrade-consistency | passed |
| pitr | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| big-data | passed |
| scaling | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| limits | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| upgrade-haproxy | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| storage | passed |
| recreate | passed |
| self-healing | failed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| scheduled-backup | failed |

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| scaling | passed |
| storage | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| big-data | passed |
| init-deploy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| affinity | passed |
| smart-update | passed |
| one-pod | passed |
| operator-self-healing | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| pitr | passed |
| tls-issue-self | passed |
| upgrade-consistency | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | passed |
| validation-hook | passed |
| scheduled-backup | failed |

**Comment by JNKPercona** [comment]
PXC operator docker - perconalab/percona-xtradb-cluster-operator:PR-720-165d2deb

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| haproxy | passed |
| init-deploy | passed |
| recreate | passed |
| limits | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| pitr | passed |
| affinity | passed |
| demand-backup-encrypted-with-tls | passed |
| one-pod | passed |
| scheduled-backup | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| big-data | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

**Review by hors — APPROVED** [review]

**Pull request merged**
