### PR TITLE
K8SPXC-813: Handle failed restore jobs

### PR DESCRIPTION
**Pull request by egegunes**
[K8SPXC-813](https://jira.percona.com/browse/K8SPXC-813) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by qJkee — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| scaling | passed |
| big-data | passed |
| scheduled-backup | passed |
| storage | passed |
| haproxy | passed |
| upgrade-haproxy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-chaos | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| self-healing-advanced | passed |
| smart-update | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| self-healing-advanced-chaos | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/928/commits/1e85a9b3b8fbebbe75e056743b5a0c1a80e432e3
image: `perconalab/percona-xtradb-cluster-operator:PR-928-1e85a9b3`

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| scheduled-backup | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| affinity | passed |
| storage | passed |
| big-data | passed |
| restore-to-encrypted-cluster | passed |
| one-pod | passed |
| self-healing | passed |
| demand-backup | passed |
| auto-tuning | passed |
| self-healing-chaos | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| self-healing-advanced | passed |
| scaling | passed |
| demand-backup-encrypted-with-tls | passed |
| users | failed |
| self-healing-advanced-chaos | passed |
| scaling-proxysql | passed |
| operator-self-healing | passed |
| security-context | passed |
| operator-self-healing-chaos | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/928/commits/1e85a9b3b8fbebbe75e056743b5a0c1a80e432e3
image: `perconalab/percona-xtradb-cluster-operator:PR-928-1e85a9b3`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| storage | passed |
| scheduled-backup | passed |
| scaling | passed |
| haproxy | passed |
| big-data | passed |
| upgrade-haproxy | passed |
| self-healing | failed |
| scaling-proxysql | passed |
| init-deploy | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| self-healing-chaos | failed |
| one-pod | passed |
| self-healing-advanced | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/928/commits/6aadc5fcb0dd01ba96473275ab387c5aa8aae31a
image: `perconalab/percona-xtradb-cluster-operator:PR-928-6aadc5fc`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| scaling | passed |
| haproxy | passed |
| scheduled-backup | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| security-context | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| big-data | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| upgrade-haproxy | passed |
| storage | passed |
| tls-issue-cert-manager-ref | passed |
| self-healing | failed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-chaos | failed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/928/commits/6aadc5fcb0dd01ba96473275ab387c5aa8aae31a
image: `perconalab/percona-xtradb-cluster-operator:PR-928-6aadc5fc`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| haproxy | passed |
| recreate | passed |
| scaling | passed |
| storage | passed |
| big-data | passed |
| scheduled-backup | passed |
| scaling-proxysql | passed |
| self-healing | failed |
| init-deploy | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| self-healing-chaos | passed |
| proxysql-sidecar-res-limits | passed |
| self-healing-advanced | passed |
| pitr | passed |
| users | passed |
| upgrade-consistency | passed |
| self-healing-advanced-chaos | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | passed |
| operator-self-healing | passed |
| validation-hook | passed |
| operator-self-healing-chaos | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/928/commits/48ab87f2bac7e5d3bf25553be831fba609ff92c5
image: `perconalab/percona-xtradb-cluster-operator:PR-928-48ab87f2`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| storage | passed |
| scheduled-backup | passed |
| recreate | passed |
| big-data | passed |
| scaling | passed |
| haproxy | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| security-context | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| monitoring-2-0 | passed |
| self-healing-chaos | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| self-healing-advanced | passed |
| one-pod | passed |
| auto-tuning | passed |
| self-healing-advanced-chaos | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| operator-self-healing | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| operator-self-healing-chaos | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/928/commits/27742b00bc748a2b69c89fce46f9ea1ab562c414
image: `perconalab/percona-xtradb-cluster-operator:PR-928-27742b00`

**Pull request merged**
