### PR TITLE
Update golange to 1.17

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1003/commits/58c9de316977690d2ebfd891d494af19ff14dcae
image: `perconalab/percona-xtradb-cluster-operator:PR-1003-58c9de31`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| storage | passed |
| recreate | passed |
| scaling | passed |
| big-data | passed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| init-deploy | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| smart-update | passed |
| monitoring-2-0 | passed |
| self-healing-advanced | passed |
| affinity | passed |
| one-pod | passed |
| self-healing-advanced-chaos | passed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| operator-self-healing | passed |
| upgrade-consistency | passed |
| operator-self-healing-chaos | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1003/commits/033773208440cc1ec87d712911e235a0dbccef1f
image: `perconalab/percona-xtradb-cluster-operator:PR-1003-03377320`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| haproxy | failed |
| scaling | passed |
| storage | passed |
| recreate | passed |
| big-data | passed |
| scheduled-backup | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| self-healing-chaos | failed |
| security-context | passed |
| init-deploy | passed |
| demand-backup | failed |
| smart-update | passed |
| self-healing-advanced | passed |
| limits | passed |
| monitoring-2-0 | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| operator-self-healing-chaos | failed |
| upgrade-consistency | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| pitr | failed |
| tls-issue-self | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1003/commits/196aa5e08f1a7dc7d1e38b5487f1ebf86d4387be
image: `perconalab/percona-xtradb-cluster-operator:PR-1003-196aa5e0`

**Review by defbin — APPROVED** [review]

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| haproxy | failed |
| upgrade-haproxy | passed |
| big-data | passed |
| storage | passed |
| scheduled-backup | passed |
| scaling | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| self-healing-chaos | failed |
| security-context | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| pitr | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| demand-backup-encrypted-with-tls | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1003/commits/196aa5e08f1a7dc7d1e38b5487f1ebf86d4387be
image: `perconalab/percona-xtradb-cluster-operator:PR-1003-196aa5e0`

**Pull request merged**
