### PR TITLE
K8SPXC-808 - Prepare main branch after 1.9.0 release

### PR DESCRIPTION
**Pull request by tplavcic**

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | failed |
| big-data | failed |
| haproxy | failed |
| scheduled-backup | failed |
| recreate | failed |
| scaling | failed |
| storage | failed |
| restore-to-encrypted-cluster | failed |
| init-deploy | failed |
| self-healing | failed |
| scaling-proxysql | failed |
| demand-backup | failed |
| self-healing-chaos | failed |
| security-context | failed |
| limits | failed |
| self-healing-advanced | failed |
| pitr | failed |
| monitoring-2-0 | failed |
| self-healing-advanced-chaos | failed |
| demand-backup-encrypted-with-tls | failed |
| affinity | failed |
| operator-self-healing | failed |
| one-pod | failed |
| operator-self-healing-chaos | failed |
| upgrade-proxysql | failed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | failed |
| users | failed |
| tls-issue-self | failed |
| tls-issue-cert-manager | failed |
| tls-issue-cert-manager-ref | failed |
| smart-update | failed |
| validation-hook | failed |
| upgrade-consistency | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/969/commits/93a95d3b240b71dc1a16773326f7bc39e5fa0be6
image: `perconalab/percona-xtradb-cluster-operator:PR-969-93a95d3b`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| big-data | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| init-deploy | passed |
| recreate | passed |
| scheduled-backup | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | failed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/969/commits/65a977c4c555c7104221a356b6101c4379035635
image: `perconalab/percona-xtradb-cluster-operator:PR-969-65a977c4`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| recreate | passed |
| scaling | passed |
| scheduled-backup | passed |
| self-healing | passed |
| haproxy | passed |
| restore-to-encrypted-cluster | passed |
| scaling-proxysql | passed |
| big-data | passed |
| self-healing-chaos | passed |
| init-deploy | passed |
| demand-backup | passed |
| security-context | passed |
| self-healing-advanced | passed |
| pitr | passed |
| limits | passed |
| upgrade-haproxy | passed |
| self-healing-advanced-chaos | passed |
| monitoring-2-0 | passed |
| demand-backup-encrypted-with-tls | passed |
| operator-self-healing | passed |
| affinity | passed |
| operator-self-healing-chaos | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/969/commits/65a977c4c555c7104221a356b6101c4379035635
image: `perconalab/percona-xtradb-cluster-operator:PR-969-65a977c4`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| scheduled-backup | passed |
| restore-to-encrypted-cluster | passed |
| haproxy | passed |
| demand-backup | passed |
| init-deploy | passed |
| pitr | passed |
| limits | passed |
| demand-backup-encrypted-with-tls | passed |
| monitoring-2-0 | passed |
| big-data | passed |
| storage | passed |
| affinity | passed |
| self-healing | passed |
| one-pod | passed |
| self-healing-chaos | passed |
| auto-tuning | passed |
| self-healing-advanced | passed |
| proxysql-sidecar-res-limits | passed |
| scaling | passed |
| self-healing-advanced-chaos | passed |
| users | passed |
| scaling-proxysql | passed |
| operator-self-healing | passed |
| tls-issue-self | passed |
| security-context | passed |
| operator-self-healing-chaos | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| upgrade-haproxy | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/969/commits/dba1916031fb201b45fa8903122923173f2bdfd8
image: `perconalab/percona-xtradb-cluster-operator:PR-969-dba19160`

**Pull request merged**
