### PR TITLE
CLOUD-615 automatically cleanup obsolete tests results in PR

### PR DESCRIPTION
**Pull request by delgod**
[CLOUD-615](https://jira.percona.com/browse/CLOUD-615) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

each time when we push to commit to PR or rerun tests the new comment is added into the GitHub PR.
As a result, we have tens of huge obsolete messages in each PR.
It is better to automatically clean up obsolete test results before push the newest test results.

### CODE REVIEW

**Comment by JNKPercona** [comment]
PXC operator docker - perconalab/percona-xtradb-cluster-operator:PR-775-352ddfc7

**Comment by JNKPercona** [comment]
PXC operator docker - perconalab/percona-xtradb-cluster-operator:PR-775-578cf036

**Comment by JNKPercona** [comment]
| Test name  | Status |\r\n| ------------- | ------------- |\r\n| upgrade-haproxy | passed |\r\n| haproxy | passed |

**Comment by JNKPercona** [comment]
PXC operator docker - perconalab/percona-xtradb-cluster-operator:PR-775-6fe64fd0

**Comment by JNKPercona** [comment]
| Test name  | Status |\r\n| ------------- | ------------- |\r\n| haproxy | passed |\r\n| upgrade-haproxy | passed |

**Comment by JNKPercona** [comment]
PXC operator docker - perconalab/percona-xtradb-cluster-operator:PR-775-b40e7da6

**Comment by JNKPercona** [comment]
| Test name  | Status |\r\n| ------------- | ------------- |\r\n| upgrade-haproxy | passed |\r\n| haproxy | passed |

**Comment by JNKPercona** [comment]
PXC operator docker - perconalab/percona-xtradb-cluster-operator:PR-775-f97d021b

**Comment by JNKPercona** [comment]
| Test name  | Status |\r\n| ------------- | ------------- |\r\n| upgrade-haproxy | passed |\r\n| haproxy | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| upgrade-haproxy | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/775/commits/bac2954d07ac2618870b3344ed0a0db804b80972
image: `perconalab/percona-xtradb-cluster-operator:PR-775-bac2954d`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| haproxy | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/775/commits/34ab9dc262ed9abba2d6e4a8d3ac8ed5aa116da7
image: `perconalab/percona-xtradb-cluster-operator:PR-775-34ab9dc2`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| upgrade-haproxy | failed |
| scaling | passed |
| storage | passed |
| upgrade-proxysql | failed |
| init-deploy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| smart-update | failed |
| security-context | passed |
| limits | failed |
| self-healing-advanced | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| upgrade-consistency | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | failed |
| tls-issue-cert-manager | failed |
| tls-issue-cert-manager-ref | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/775/commits/aa81e3bf11160d4b7fa307a77a4bb64119a2b560
image: `perconalab/percona-xtradb-cluster-operator:PR-775-aa81e3bf`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/775/commits/aa81e3bf11160d4b7fa307a77a4bb64119a2b560
image: `perconalab/percona-xtradb-cluster-operator:PR-775-aa81e3bf`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| scheduled-backup | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/775/commits/aa81e3bf11160d4b7fa307a77a4bb64119a2b560
image: `perconalab/percona-xtradb-cluster-operator:PR-775-aa81e3bf`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/775/commits/a6e346e11b77380decc14c22daed107de2e1ef85
image: `perconalab/percona-xtradb-cluster-operator:PR-775-a6e346e1`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| big-data | passed |
| scaling | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| limits | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/775/commits/2bee3da41cf357b7f4423223374e5be6cedf666b
image: `perconalab/percona-xtradb-cluster-operator:PR-775-2bee3da4`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/775/commits/2bee3da41cf357b7f4423223374e5be6cedf666b
image: `perconalab/percona-xtradb-cluster-operator:PR-775-2bee3da4`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| big-data | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/775/commits/2bee3da41cf357b7f4423223374e5be6cedf666b
image: `perconalab/percona-xtradb-cluster-operator:PR-775-2bee3da4`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| scaling | passed |
| scaling-proxysql | passed |
| big-data | passed |
| security-context | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | failed |
| demand-backup | passed |
| smart-update | passed |
| operator-self-healing | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-consistency | passed |
| scheduled-backup | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/775/commits/2bee3da41cf357b7f4423223374e5be6cedf666b
image: `perconalab/percona-xtradb-cluster-operator:PR-775-2bee3da4`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/775/commits/2bee3da41cf357b7f4423223374e5be6cedf666b
image: `perconalab/percona-xtradb-cluster-operator:PR-775-2bee3da4`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| storage | passed |
| self-healing | passed |
| scaling | passed |
| upgrade-haproxy | passed |
| self-healing-advanced | failed |
| scaling-proxysql | passed |
| security-context | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| operator-self-healing | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/775/commits/2bee3da41cf357b7f4423223374e5be6cedf666b
image: `perconalab/percona-xtradb-cluster-operator:PR-775-2bee3da4`

**Review by hors — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| storage | passed |
| scheduled-backup | failed |
| self-healing | passed |
| self-healing-advanced | failed |
| scaling | passed |
| big-data | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| operator-self-healing | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/775/commits/2bee3da41cf357b7f4423223374e5be6cedf666b
image: `perconalab/percona-xtradb-cluster-operator:PR-775-2bee3da4`

**Review by tplavcic — APPROVED** [review]

**Pull request merged**
