### PR TITLE
update to go 1.17 and fix go-licenses check

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | failed |
| scaling | passed |
| recreate | failed |
| upgrade-haproxy | failed |
| scheduled-backup | failed |
| storage | passed |
| haproxy | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| scaling-proxysql | passed |
| init-deploy | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| upgrade-proxysql | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| restore-to-encrypted-cluster | failed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| smart-update | failed |
| demand-backup | failed |
| upgrade-consistency | passed |
| pitr | failed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1090/commits/6b3093bc66d4ee2c2d1efe5aa3fb65adeeac27a7
image: `perconalab/percona-xtradb-cluster-operator:PR-1090-6b3093bc`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| recreate | passed |
| scaling | passed |
| haproxy | passed |
| storage | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| self-healing | passed |
| security-context | passed |
| limits | passed |
| self-healing-chaos | failed |
| monitoring-2-0 | passed |
| affinity | passed |
| big-data | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| scheduled-backup | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| restore-to-encrypted-cluster | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| upgrade-proxysql | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| demand-backup | passed |
| smart-update | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | failed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1090/commits/6b3093bc66d4ee2c2d1efe5aa3fb65adeeac27a7
image: `perconalab/percona-xtradb-cluster-operator:PR-1090-6b3093bc`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| upgrade-haproxy | passed |
| storage | passed |
| restore-to-encrypted-cluster | passed |
| self-healing | passed |
| demand-backup | passed |
| self-healing-chaos | failed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| scaling | passed |
| scheduled-backup | passed |
| big-data | passed |
| scaling-proxysql | passed |
| security-context | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1090/commits/6b3093bc66d4ee2c2d1efe5aa3fb65adeeac27a7
image: `perconalab/percona-xtradb-cluster-operator:PR-1090-6b3093bc`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| storage | passed |
| big-data | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| security-context | passed |
| self-healing-chaos | failed |
| haproxy | passed |
| recreate | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| scheduled-backup | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| pitr | passed |
| affinity | passed |
| demand-backup-encrypted-with-tls | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| upgrade-haproxy | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1090/commits/6b3093bc66d4ee2c2d1efe5aa3fb65adeeac27a7
image: `perconalab/percona-xtradb-cluster-operator:PR-1090-6b3093bc`

**Pull request merged**
