### PR TITLE
CLOUD-654 - don't set defaults in CR

### PR DESCRIPTION
**Pull request by delgod**
[CLOUD-654](https://jira.percona.com/browse/CLOUD-654) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | failed |
| scaling | failed |
| scheduled-backup | failed |
| upgrade-haproxy | failed |
| recreate | failed |
| haproxy | failed |
| storage | failed |
| self-healing | passed |
| self-healing-chaos | failed |
| scaling-proxysql | failed |
| init-deploy | failed |
| restore-to-encrypted-cluster | failed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| limits | passed |
| demand-backup | failed |
| security-context | failed |
| monitoring-2-0 | failed |
| pitr | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | failed |
| demand-backup-encrypted-with-tls | failed |
| upgrade-proxysql | failed |
| proxysql-sidecar-res-limits | failed |
| users | failed |
| tls-issue-self | failed |
| tls-issue-cert-manager | failed |
| tls-issue-cert-manager-ref | failed |
| validation-hook | passed |
| smart-update | failed |
| upgrade-consistency | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1053/commits/959f20a495d90661a63fb31a4540b277a9a00495
image: `perconalab/percona-xtradb-cluster-operator:PR-1053-959f20a4`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| big-data | passed |
| storage | passed |
| scaling | passed |
| scheduled-backup | failed |
| recreate | passed |
| haproxy | failed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| pitr | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1053/commits/959f20a495d90661a63fb31a4540b277a9a00495
image: `perconalab/percona-xtradb-cluster-operator:PR-1053-959f20a4`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | failed |
| storage | failed |
| scheduled-backup | failed |
| recreate | failed |
| scaling | failed |
| upgrade-haproxy | failed |
| big-data | failed |
| self-healing | passed |
| self-healing-chaos | failed |
| scaling-proxysql | failed |
| init-deploy | failed |
| restore-to-encrypted-cluster | failed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| security-context | failed |
| limits | passed |
| demand-backup | failed |
| monitoring-2-0 | failed |
| pitr | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | failed |
| demand-backup-encrypted-with-tls | failed |
| upgrade-proxysql | failed |
| proxysql-sidecar-res-limits | failed |
| users | failed |
| tls-issue-self | failed |
| tls-issue-cert-manager | failed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1053/commits/93a04c911e1d41c91293045b7494b80b9eb7a056
image: `perconalab/percona-xtradb-cluster-operator:PR-1053-93a04c91`

**Review by egegunes — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | failed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| big-data | passed |
| storage | passed |
| recreate | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| init-deploy | passed |
| demand-backup | passed |
| limits | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| pitr | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1053/commits/93a04c911e1d41c91293045b7494b80b9eb7a056
image: `perconalab/percona-xtradb-cluster-operator:PR-1053-93a04c91`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| big-data | passed |
| scaling | passed |
| storage | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| security-context | passed |
| self-healing-chaos | failed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1053/commits/93a04c911e1d41c91293045b7494b80b9eb7a056
image: `perconalab/percona-xtradb-cluster-operator:PR-1053-93a04c91`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| haproxy | failed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| big-data | passed |
| scheduled-backup | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-haproxy | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1053/commits/93a04c911e1d41c91293045b7494b80b9eb7a056
image: `perconalab/percona-xtradb-cluster-operator:PR-1053-93a04c91`

**Pull request merged**
