### PR TITLE
K8SPXC-707: read current gtid from sst_info file

### PR DESCRIPTION
**Pull request by qJkee**
[K8SPXC-707](https://jira.percona.com/browse/K8SPXC-707) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| big-data | passed |
| haproxy | passed |
| recreate | passed |
| storage | passed |
| scaling | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| one-pod | passed |
| operator-self-healing | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/852/commits/69c0eee79919f11f0d98af18ca4073c2ff36f635
image: `perconalab/percona-xtradb-cluster-operator:PR-852-69c0eee7`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| big-data | passed |
| haproxy | passed |
| init-deploy | passed |
| upgrade-haproxy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| storage | passed |
| tls-issue-self | passed |
| self-healing | passed |
| tls-issue-cert-manager | passed |
| self-healing-advanced | passed |
| tls-issue-cert-manager-ref | passed |
| operator-self-healing | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/852/commits/69c0eee79919f11f0d98af18ca4073c2ff36f635
image: `perconalab/percona-xtradb-cluster-operator:PR-852-69c0eee7`

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| scaling | passed |
| recreate | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| scheduled-backup | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/852/commits/69c0eee79919f11f0d98af18ca4073c2ff36f635
image: `perconalab/percona-xtradb-cluster-operator:PR-852-69c0eee7`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| big-data | passed |
| upgrade-haproxy | passed |
| storage | passed |
| recreate | passed |
| scaling | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| self-healing | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| operator-self-healing | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | failed |
| pitr | passed |
| users | failed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| scheduled-backup | failed |
| tls-issue-self | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/852/commits/9af5b3e0a0021e4b35ce53b8c48eb6b885cf6ecf
image: `perconalab/percona-xtradb-cluster-operator:PR-852-9af5b3e0`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| haproxy | passed |
| big-data | passed |
| recreate | passed |
| scaling | passed |
| storage | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| self-healing | passed |
| limits | passed |
| monitoring-2-0 | passed |
| self-healing-advanced | passed |
| smart-update | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| operator-self-healing | failed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-consistency | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| scheduled-backup | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/852/commits/c76a820d548252af2ddbe61b2be07ede41162f88
image: `perconalab/percona-xtradb-cluster-operator:PR-852-c76a820d`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-haproxy | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/852/commits/9af5b3e0a0021e4b35ce53b8c48eb6b885cf6ecf
image: `perconalab/percona-xtradb-cluster-operator:PR-852-9af5b3e0`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| scaling | passed |
| recreate | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| scheduled-backup | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| upgrade-proxysql | passed |
| users | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/852/commits/9af5b3e0a0021e4b35ce53b8c48eb6b885cf6ecf
image: `perconalab/percona-xtradb-cluster-operator:PR-852-9af5b3e0`

**Review by nonemax — APPROVED** [review]

**Review by delgod — DISMISSED** [review]

**Pull request merged**
