### PR TITLE
K8SPXC-758 fix: `operator-sdk generate k8s`

### PR DESCRIPTION
**Pull request by pooknull**
[K8SPXC-758](https://jira.percona.com/browse/K8SPXC-758) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

https://jira.percona.com/browse/K8SPXC-758

### CODE REVIEW

**Review by delgod — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | passed |
| big-data | passed |
| scaling | passed |
| storage | passed |
| haproxy | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| self-healing-chaos | failed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| affinity | passed |
| smart-update | passed |
| one-pod | passed |
| pitr | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1092/commits/3c755e36af7ca470ce5e5b3df18cfc3e807a15eb
image: `perconalab/percona-xtradb-cluster-operator:PR-1092-3c755e36`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | passed |
| scaling | passed |
| scaling-proxysql | passed |
| big-data | passed |
| haproxy | passed |
| security-context | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| upgrade-haproxy | passed |
| recreate | passed |
| storage | passed |
| one-pod | passed |
| restore-to-encrypted-cluster | passed |
| self-healing | passed |
| auto-tuning | passed |
| demand-backup | passed |
| self-healing-chaos | failed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1092/commits/3c755e36af7ca470ce5e5b3df18cfc3e807a15eb
image: `perconalab/percona-xtradb-cluster-operator:PR-1092-3c755e36`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| haproxy | passed |
| scheduled-backup | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| storage | passed |
| auto-tuning | passed |
| self-healing | passed |
| proxysql-sidecar-res-limits | passed |
| self-healing-chaos | failed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| scaling | passed |
| recreate | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| big-data | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1092/commits/3c755e36af7ca470ce5e5b3df18cfc3e807a15eb
image: `perconalab/percona-xtradb-cluster-operator:PR-1092-3c755e36`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| storage | passed |
| recreate | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| self-healing-chaos | failed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| haproxy | passed |
| big-data | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1092/commits/3c755e36af7ca470ce5e5b3df18cfc3e807a15eb
image: `perconalab/percona-xtradb-cluster-operator:PR-1092-3c755e36`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scheduled-backup | passed |
| haproxy | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| security-context | passed |
| limits | passed |
| monitoring-2-0 | passed |
| big-data | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| storage | passed |
| affinity | passed |
| restore-to-encrypted-cluster | passed |
| self-healing | passed |
| one-pod | passed |
| demand-backup | passed |
| self-healing-chaos | failed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| demand-backup-encrypted-with-tls | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1092/commits/3c755e36af7ca470ce5e5b3df18cfc3e807a15eb
image: `perconalab/percona-xtradb-cluster-operator:PR-1092-3c755e36`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1092/commits/b4f63280c2e085496c65c60669b158efe8b5a997
image: `perconalab/percona-xtradb-cluster-operator:PR-1092-b4f63280`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| upgrade-haproxy | passed |
| big-data | failed |
| self-healing | passed |
| self-healing-chaos | failed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1092/commits/b4f63280c2e085496c65c60669b158efe8b5a997
image: `perconalab/percona-xtradb-cluster-operator:PR-1092-b4f63280`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| recreate | passed |
| big-data | failed |
| storage | passed |
| scaling | passed |
| haproxy | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| upgrade-proxysql | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | failed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| smart-update | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-consistency | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1092/commits/b4f63280c2e085496c65c60669b158efe8b5a997
image: `perconalab/percona-xtradb-cluster-operator:PR-1092-b4f63280`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| haproxy | passed |
| recreate | passed |
| big-data | passed |
| operator-self-healing-chaos | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-haproxy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| affinity | passed |
| scaling-proxysql | passed |
| one-pod | passed |
| security-context | passed |
| auto-tuning | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| proxysql-sidecar-res-limits | passed |
| demand-backup | passed |
| users | passed |
| pitr | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| demand-backup-encrypted-with-tls | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1092/commits/b4f63280c2e085496c65c60669b158efe8b5a997
image: `perconalab/percona-xtradb-cluster-operator:PR-1092-b4f63280`

**Review by delgod — APPROVED** [review]

**Pull request merged**
