### PR TITLE
K8SPXC-568 feature: Restrict running more than 5 pods of PXC if unsafe flag is not set

### PR DESCRIPTION
**Pull request by pooknull**
[K8SPXC-568](https://jira.percona.com/browse/K8SPXC-568) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

https://jira.percona.com/browse/K8SPXC-568

Modified validation to restrict running more than 5 pods of PXC unless allowUnsafeConfigurations flag is set to true by changing PXC size to 5 if it's higher than that.

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| big-data | passed |
| recreate | passed |
| scaling | passed |
| init-deploy | passed |
| self-healing | failed |
| scaling-proxysql | failed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| self-healing-advanced | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| operator-self-healing | passed |
| users | failed |
| pitr | failed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/843/commits/8eeb03bde81ea3f46d2a799053ceb93ee688a1e2
image: `perconalab/percona-xtradb-cluster-operator:PR-843-8eeb03bd`

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| recreate | passed |
| big-data | passed |
| scaling | passed |
| haproxy | passed |
| storage | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| demand-backup | passed |
| smart-update | passed |
| monitoring-2-0 | passed |
| operator-self-healing | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| scheduled-backup | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/843/commits/822e67b120b17e137f4597d6c11256945a5f0bb5
image: `perconalab/percona-xtradb-cluster-operator:PR-843-822e67b1`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| big-data | passed |
| scaling-proxysql | passed |
| security-context | passed |
| storage | passed |
| upgrade-haproxy | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/843/commits/822e67b120b17e137f4597d6c11256945a5f0bb5
image: `perconalab/percona-xtradb-cluster-operator:PR-843-822e67b1`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| upgrade-haproxy | passed |
| scaling-proxysql | passed |
| security-context | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| big-data | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/843/commits/822e67b120b17e137f4597d6c11256945a5f0bb5
image: `perconalab/percona-xtradb-cluster-operator:PR-843-822e67b1`

**Review by qJkee — APPROVED** [review]

**Review by blez — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| upgrade-haproxy | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| scaling | passed |
| one-pod | passed |
| storage | passed |
| auto-tuning | passed |
| scaling-proxysql | passed |
| recreate | passed |
| self-healing | passed |
| proxysql-sidecar-res-limits | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| self-healing-advanced | passed |
| big-data | passed |
| users | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| tls-issue-self | passed |
| pitr | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager-ref | passed |
| scheduled-backup | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/843/commits/822e67b120b17e137f4597d6c11256945a5f0bb5
image: `perconalab/percona-xtradb-cluster-operator:PR-843-822e67b1`

**Pull request merged**
