### PR TITLE
K8SPXC-821 tests: custom config from secret is not mounted to proxysql

### PR DESCRIPTION
**Pull request by pooknull**
[K8SPXC-821](https://jira.percona.com/browse/K8SPXC-821) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

https://jira.percona.com/browse/K8SPXC-821

Modified tests to check configuration values after adding secret with config

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| storage | failed |
| recreate | passed |
| big-data | passed |
| scheduled-backup | passed |
| scaling | passed |
| haproxy | failed |
| scaling-proxysql | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| security-context | failed |
| upgrade-proxysql | failed |
| init-deploy | failed |
| self-healing-chaos | failed |
| demand-backup | passed |
| self-healing-advanced | passed |
| smart-update | passed |
| limits | failed |
| monitoring-2-0 | passed |
| self-healing-advanced-chaos | failed |
| affinity | failed |
| operator-self-healing | passed |
| pitr | passed |
| one-pod | passed |
| operator-self-healing-chaos | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | failed |
| upgrade-consistency | failed |
| users | failed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/944/commits/17a843504448568352250c08619b530248f8488e
image: `perconalab/percona-xtradb-cluster-operator:PR-944-17a84350`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | failed |
| scheduled-backup | passed |
| big-data | passed |
| storage | passed |
| scaling | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| init-deploy | passed |
| upgrade-proxysql | passed |
| self-healing-chaos | passed |
| demand-backup | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| self-healing-advanced-chaos | passed |
| one-pod | passed |
| pitr | passed |
| auto-tuning | passed |
| operator-self-healing | passed |
| proxysql-sidecar-res-limits | passed |
| operator-self-healing-chaos | passed |
| users | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/944/commits/7a67862c3c16911eaf48bdac89fdf0944679990c
image: `perconalab/percona-xtradb-cluster-operator:PR-944-7a67862c`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| upgrade-haproxy | passed |
| restore-to-encrypted-cluster | passed |
| storage | passed |
| demand-backup | passed |
| self-healing | passed |
| pitr | passed |
| self-healing-chaos | passed |
| scheduled-backup | passed |
| demand-backup-encrypted-with-tls | passed |
| self-healing-advanced | passed |
| haproxy | failed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scaling | passed |
| big-data | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/944/commits/7a67862c3c16911eaf48bdac89fdf0944679990c
image: `perconalab/percona-xtradb-cluster-operator:PR-944-7a67862c`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| haproxy | failed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/944/commits/7a67862c3c16911eaf48bdac89fdf0944679990c
image: `perconalab/percona-xtradb-cluster-operator:PR-944-7a67862c`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| recreate | passed |
| storage | passed |
| haproxy | failed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| big-data | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-chaos | passed |
| init-deploy | passed |
| self-healing-advanced | passed |
| smart-update | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| self-healing-advanced-chaos | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| operator-self-healing | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | failed |
| upgrade-consistency | passed |
| operator-self-healing-chaos | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-self | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/944/commits/6ba38481abb9854f17bb274e5c35402836232a91
image: `perconalab/percona-xtradb-cluster-operator:PR-944-6ba38481`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | failed |
| upgrade-haproxy | passed |
| recreate | passed |
| scaling | passed |
| big-data | passed |
| restore-to-encrypted-cluster | passed |
| scaling-proxysql | passed |
| demand-backup | passed |
| security-context | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| scheduled-backup | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/944/commits/6ba38481abb9854f17bb274e5c35402836232a91
image: `perconalab/percona-xtradb-cluster-operator:PR-944-6ba38481`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| recreate | passed |
| storage | passed |
| restore-to-encrypted-cluster | passed |
| self-healing | passed |
| demand-backup | passed |
| self-healing-chaos | passed |
| pitr | passed |
| self-healing-advanced | passed |
| demand-backup-encrypted-with-tls | passed |
| self-healing-advanced-chaos | passed |
| scaling | passed |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| scaling-proxysql | passed |
| operator-self-healing-chaos | passed |
| security-context | passed |
| big-data | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/944/commits/6ba38481abb9854f17bb274e5c35402836232a91
image: `perconalab/percona-xtradb-cluster-operator:PR-944-6ba38481`

**Review by qJkee — APPROVED** [review]

**Review by delgod — APPROVED** [review]

**Pull request merged**
