### PR TITLE
K8SPXC-816 fix sporadic issues with resolver

### PR DESCRIPTION
**Pull request by delgod**
[K8SPXC-816](https://jira.percona.com/browse/K8SPXC-816) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

use 127.0.0.1 explicitly

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | failed |
| scaling | failed |
| recreate | failed |
| scheduled-backup | failed |
| upgrade-haproxy | failed |
| big-data | failed |
| storage | failed |
| init-deploy | failed |
| scaling-proxysql | failed |
| restore-to-encrypted-cluster | failed |
| self-healing | failed |
| security-context | failed |
| demand-backup | failed |
| limits | failed |
| self-healing-chaos | failed |
| self-healing-advanced | failed |
| monitoring-2-0 | failed |
| pitr | failed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | failed |
| affinity | failed |
| demand-backup-encrypted-with-tls | failed |
| operator-self-healing-chaos | failed |
| upgrade-proxysql | failed |
| one-pod | failed |
| auto-tuning | failed |
| proxysql-sidecar-res-limits | failed |
| users | failed |
| tls-issue-self | failed |
| tls-issue-cert-manager | failed |
| tls-issue-cert-manager-ref | failed |
| smart-update | failed |
| validation-hook | passed |
| upgrade-consistency | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/920/commits/2fe0d1ac4c1927b4b1497916c8fe16fdf47eba99
image: `perconalab/percona-xtradb-cluster-operator:PR-920-2fe0d1ac`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| scaling | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| scheduled-backup | passed |
| big-data | passed |
| storage | passed |
| init-deploy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| security-context | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| self-healing-chaos | passed |
| one-pod | passed |
| auto-tuning | passed |
| self-healing-advanced | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| self-healing-advanced-chaos | passed |
| tls-issue-self | passed |
| operator-self-healing | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager-ref | passed |
| operator-self-healing-chaos | passed |
| validation-hook | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/920/commits/97385c71bc710a68ce21638e878b0578fd6ae97c
image: `perconalab/percona-xtradb-cluster-operator:PR-920-97385c71`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | failed |
| upgrade-haproxy | passed |
| haproxy | passed |
| big-data | passed |
| scaling | passed |
| storage | passed |
| recreate | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-chaos | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| self-healing-advanced | passed |
| affinity | passed |
| one-pod | passed |
| self-healing-advanced-chaos | failed |
| auto-tuning | passed |
| pitr | passed |
| operator-self-healing | passed |
| upgrade-consistency | passed |
| operator-self-healing-chaos | failed |
| proxysql-sidecar-res-limits | passed |
| demand-backup-encrypted-with-tls | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/920/commits/71105c760339fde32e8f0545341f9d55ddd6d4f2
image: `perconalab/percona-xtradb-cluster-operator:PR-920-71105c76`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| big-data | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| haproxy | passed |
| scaling | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| limits | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| upgrade-haproxy | passed |
| storage | passed |
| auto-tuning | passed |
| self-healing | passed |
| scheduled-backup | passed |
| proxysql-sidecar-res-limits | passed |
| self-healing-chaos | passed |
| users | passed |
| self-healing-advanced | passed |
| tls-issue-self | passed |
| self-healing-advanced-chaos | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/920/commits/71105c760339fde32e8f0545341f9d55ddd6d4f2
image: `perconalab/percona-xtradb-cluster-operator:PR-920-71105c76`

**Review by hors — APPROVED** [review]

**Pull request merged**
