### PR TITLE
Rename helm delete to uninstall and put timeout to chaos-mesh delete

### PR DESCRIPTION
**Pull request by tplavcic**
`--purge` option doesn't exist any more for helm del and delete was renamed to uninstall so better to use it (https://helm.sh/docs/helm/helm_delete/).
Put a timeout to chaos-mesh delete and do not try to remove it on every namespace removal (there's a bug with stall when networkchaos crd is tried to delete).

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| haproxy | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| scheduled-backup | failed |
| big-data | passed |
| scaling | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| smart-update | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| pitr | failed |
| proxysql-sidecar-res-limits | failed |
| demand-backup-encrypted-with-tls | failed |
| users | failed |
| upgrade-consistency | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1076/commits/5088266e650b544808f38641cadd9eaabea1e63b
image: `perconalab/percona-xtradb-cluster-operator:PR-1076-5088266e`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| big-data | passed |
| scaling | passed |
| recreate | passed |
| storage | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| demand-backup | passed |
| smart-update | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1076/commits/ea9279b3c2fcc96abc41b2f88388a6642821e735
image: `perconalab/percona-xtradb-cluster-operator:PR-1076-ea9279b3`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| scheduled-backup | passed |
| storage | passed |
| scaling | passed |
| haproxy | passed |
| big-data | passed |
| upgrade-haproxy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| demand-backup | passed |
| smart-update | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| affinity | passed |
| one-pod | passed |
| pitr | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| upgrade-consistency | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1076/commits/a54d0de5dfa592fe1061c9192c478d1735c18649
image: `perconalab/percona-xtradb-cluster-operator:PR-1076-a54d0de5`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-haproxy | passed |
| storage | passed |
| big-data | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| scaling | passed |
| haproxy | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| security-context | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| scheduled-backup | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1076/commits/a54d0de5dfa592fe1061c9192c478d1735c18649
image: `perconalab/percona-xtradb-cluster-operator:PR-1076-a54d0de5`

**Review by delgod — APPROVED** [review]

**Pull request merged**
