### PR TITLE
K8SPXC-876 use PublishNotReadyAddresses instead of annotation

### PR DESCRIPTION
**Pull request by delgod**
[K8SPXC-876](https://jira.percona.com/browse/K8SPXC-876) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

https://jira.percona.com/browse/K8SPXC-876
"service.alpha.kubernetes.io/tolerate-unready-endpoints" annotation has been
deprecated since Kuberneets 1.8 and the spec.publishNotReadyAddresses
parameter replacing it has been correctly implemented in Kubernetes 1.11
(see kubernetes/kubernetes#63742)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| haproxy | failed |
| storage | passed |
| scaling | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| init-deploy | failed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-chaos | failed |
| self-healing-advanced | passed |
| limits | passed |
| smart-update | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| self-healing-advanced-chaos | failed |
| operator-self-healing | passed |
| one-pod | passed |
| auto-tuning | passed |
| operator-self-healing-chaos | failed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/995/commits/c1004802290f90c6d8079472177b5d50dcb17e12
image: `perconalab/percona-xtradb-cluster-operator:PR-995-c1004802`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| scaling | passed |
| big-data | passed |
| storage | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| security-context | passed |
| self-healing-chaos | failed |
| recreate | passed |
| upgrade-proxysql | passed |
| init-deploy | failed |
| restore-to-encrypted-cluster | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | failed |
| smart-update | passed |
| upgrade-consistency | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| demand-backup | passed |
| pitr | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/995/commits/c1004802290f90c6d8079472177b5d50dcb17e12
image: `perconalab/percona-xtradb-cluster-operator:PR-995-c1004802`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scheduled-backup | passed |
| upgrade-haproxy | passed |
| big-data | passed |
| recreate | passed |
| storage | passed |
| haproxy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| self-healing-advanced | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| self-healing-advanced-chaos | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| tls-issue-self | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/995/commits/5ab394b7bdb31f93734c6a29b9fd474ab313e809
image: `perconalab/percona-xtradb-cluster-operator:PR-995-5ab394b7`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| recreate | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| self-healing-chaos | passed |
| demand-backup | passed |
| self-healing-advanced | passed |
| pitr | passed |
| upgrade-haproxy | passed |
| self-healing-advanced-chaos | passed |
| demand-backup-encrypted-with-tls | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| haproxy | passed |
| big-data | passed |
| scaling | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| limits | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/995/commits/5ab394b7bdb31f93734c6a29b9fd474ab313e809
image: `perconalab/percona-xtradb-cluster-operator:PR-995-5ab394b7`

**Review by defbin — APPROVED** [review]

**Review by nonemax — APPROVED** [review]

**Pull request merged**
