### PR TITLE
Update cer-manager for e2e tests

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | failed |
| scheduled-backup | passed |
| storage | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| recreate | passed |
| big-data | passed |
| init-deploy | passed |
| scaling-proxysql | failed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| security-context | passed |
| demand-backup | passed |
| limits | passed |
| smart-update | passed |
| monitoring-2-0 | passed |
| self-healing-chaos | failed |
| affinity | passed |
| one-pod | passed |
| self-healing-advanced | passed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | passed |
| self-healing-advanced-chaos | failed |
| users | passed |
| operator-self-healing | passed |
| upgrade-consistency | passed |
| operator-self-healing-chaos | failed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/990/commits/268a0c1f41dc2263c3943c501e6ce82d01d8c6f4
image: `perconalab/percona-xtradb-cluster-operator:PR-990-268a0c1f`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| big-data | passed |
| upgrade-haproxy | passed |
| storage | passed |
| scaling | passed |
| scheduled-backup | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| self-healing-chaos | passed |
| demand-backup | passed |
| self-healing-advanced | passed |
| smart-update | passed |
| self-healing-advanced-chaos | passed |
| pitr | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/990/commits/8a2f7e143b9728aa1f6964d630b4fa0c2e53ccba
image: `perconalab/percona-xtradb-cluster-operator:PR-990-8a2f7e14`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| storage | passed |
| scaling | passed |
| scheduled-backup | passed |
| recreate | passed |
| haproxy | passed |
| big-data | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| init-deploy | passed |
| upgrade-proxysql | passed |
| security-context | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | failed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| one-pod | passed |
| self-healing-advanced-chaos | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| operator-self-healing | passed |
| users | passed |
| upgrade-consistency | passed |
| operator-self-healing-chaos | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/990/commits/f86d37e0dd8d6cb807a3ceec98a136ceec5f3016
image: `perconalab/percona-xtradb-cluster-operator:PR-990-f86d37e0`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| big-data | passed |
| recreate | passed |
| storage | passed |
| scheduled-backup | passed |
| restore-to-encrypted-cluster | passed |
| self-healing | passed |
| demand-backup | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| scaling | passed |
| operator-self-healing-chaos | passed |
| scaling-proxysql | passed |
| security-context | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/990/commits/f86d37e0dd8d6cb807a3ceec98a136ceec5f3016
image: `perconalab/percona-xtradb-cluster-operator:PR-990-f86d37e0`

**Review by delgod — APPROVED** [review]

**Pull request merged**
