### PR TITLE
K8SPXC-474: add resource requests to init containers

### PR DESCRIPTION
**Pull request by qJkee**
[K8SPXC-474](https://jira.percona.com/browse/K8SPXC-474)

Add resource requests to init containers since some of the systems require it

### CODE REVIEW

**Comment by JNKPercona** [comment]
PXC operator docker - perconalab/percona-xtradb-cluster-operator:PR-611-f0bf9324

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| scaling | passed |
| storage | passed |
| big-data | passed |
| recreate | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| security-context | passed |
| limits | passed |
| operator-self-healing | passed |
| demand-backup | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| scheduled-backup | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| haproxy | passed |
| storage | passed |
| big-data | passed |
| scaling | passed |
| self-healing | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring | passed |
| upgrade-consistency | passed |
| security-context | passed |
| operator-self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| scheduled-backup | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |

**Review by dAdAbird — CHANGES_REQUESTED** [review]
I think the user should be able to set resources for those containers via cr.yaml. I doubt that resources should be hardcoded.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

**Review by delgod — DISMISSED** [review]

**Review by delgod — DISMISSED** [review]

**Review by dAdAbird — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| recreate | passed |
| big-data | passed |
| scaling | passed |
| storage | failed |
| scaling-proxysql | passed |
| init-deploy | failed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | failed |
| monitoring | failed |
| upgrade-consistency | failed |
| self-healing-advanced | passed |
| security-context | failed |
| operator-self-healing | passed |
| monitoring-2-0 | failed |
| demand-backup | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| scheduled-backup | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-cert-manager-ref | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| storage | failed |
| scaling | passed |
| big-data | passed |
| recreate | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| init-deploy | failed |
| upgrade-consistency | failed |
| security-context | failed |
| limits | failed |
| monitoring | failed |
| self-healing-advanced | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| monitoring-2-0 | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| scheduled-backup | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| recreate | passed |
| big-data | passed |
| haproxy | passed |
| scaling | passed |
| init-deploy | failed |
| scaling-proxysql | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | failed |
| self-healing-advanced | passed |
| monitoring | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| upgrade-consistency | failed |
| monitoring-2-0 | passed |
| affinity | failed |
| security-context | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| scheduled-backup | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | passed |

**Review by hors — CHANGES_REQUESTED** [review]
@qJkee  please check and fix tests

**Comment by qJkee** [comment]
> @qJkee please check and fix tests

i see that tests are not passing and i'm already fixing them

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| scaling | passed |
| recreate | passed |
| haproxy | passed |
| storage | failed |
| init-deploy | failed |
| scaling-proxysql | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | failed |
| self-healing-advanced | passed |
| upgrade-consistency | failed |
| monitoring | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| security-context | failed |
| monitoring-2-0 | passed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| scheduled-backup | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager-ref | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| storage | passed |
| big-data | passed |
| haproxy | passed |
| scaling | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| upgrade | passed |
| limits | passed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| monitoring | passed |
| security-context | failed |
| operator-self-healing | passed |
| demand-backup | failed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| scheduled-backup | failed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |

**Review by delgod — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| scaling | passed |
| recreate | passed |
| haproxy | passed |
| storage | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | failed |
| init-deploy | passed |
| self-healing-advanced | passed |
| upgrade-consistency | passed |
| security-context | failed |
| limits | passed |
| operator-self-healing | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| monitoring | passed |
| scaling-proxysql | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| upgrade | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| auto-tuning | passed |
| security-context | failed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| recreate | passed |
| tls-issue-self | passed |
| restore-to-encrypted-cluster | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| storage | passed |
| big-data | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| demand-backup | failed |
| scheduled-backup | failed |
| demand-backup-encrypted-with-tls | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| scaling | passed |
| big-data | passed |
| auto-tuning | passed |
| scaling-proxysql | passed |
| proxysql-sidecar-res-limits | passed |
| upgrade | passed |
| users | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| security-context | failed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |

**Comment by JNKPercona** [comment]
PXC operator docker - perconalab/percona-xtradb-cluster-operator:PR-611-77257bd2

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| scaling | passed |
| restore-to-encrypted-cluster | passed |
| scaling-proxysql | passed |
| storage | passed |
| demand-backup | passed |
| upgrade | passed |
| haproxy | passed |
| self-healing | passed |
| upgrade-consistency | passed |
| init-deploy | passed |
| self-healing-advanced | passed |
| security-context | passed |
| limits | passed |
| big-data | passed |
| operator-self-healing | passed |
| monitoring | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| scheduled-backup | passed |
| demand-backup-encrypted-with-tls | passed |

**Review by hors — APPROVED** [review]

**Pull request merged**
