### PR TITLE
Update after PXC 1.6.0 release and prepare for 1.7.0

### PR DESCRIPTION
**Pull request by tplavcic**
haproxy and monitoring-2.0 are failing with diff issue because of this fix: https://github.com/percona/percona-xtradb-cluster-operator/commit/32e6fa19ded2f2c148cc19a043f3d2e787ecd323
```
+ diff -u /mnt/jenkins/workspace/cloud-pxc-operator_PR-637/e2e-tests/haproxy/compare/statefulset_haproxy-haproxy.yml /tmp/tmp.lQln2oT2QJ/statefulset_haproxy-haproxy.yml
--- /mnt/jenkins/workspace/cloud-pxc-operator_PR-637/e2e-tests/haproxy/compare/statefulset_haproxy-haproxy.yml	2020-10-13 05:27:25.805522784 +0000
+++ /tmp/tmp.lQln2oT2QJ/statefulset_haproxy-haproxy.yml	2020-10-13 05:44:54.405369014 +0000
@@ -109,7 +109,6 @@
       securityContext: {}
       serviceAccount: default
       serviceAccountName: default
-      shareProcessNamespace: true
       terminationGracePeriodSeconds: 30
       tolerations:
         - effect: NoExecute
```

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | failed |
| scaling | failed |
| big-data | failed |
| storage | failed |
| restore-to-encrypted-cluster | failed |
| haproxy | failed |
| self-healing | failed |
| scaling-proxysql | failed |
| demand-backup | failed |
| init-deploy | failed |
| self-healing-advanced | failed |
| upgrade | failed |
| operator-self-healing | failed |
| limits | failed |
| scheduled-backup | failed |
| monitoring | failed |
| monitoring-2-0 | failed |
| demand-backup-encrypted-with-tls | failed |
| affinity | failed |
| one-pod | failed |
| auto-tuning | failed |
| upgrade-consistency | failed |
| proxysql-sidecar-res-limits | failed |
| users | failed |
| tls-issue-self | failed |
| tls-issue-cert-manager | failed |
| tls-issue-cert-manager-ref | failed |
| security-context | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| big-data | passed |
| storage | passed |
| recreate | passed |
| haproxy | passed |
| self-healing | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| self-healing-advanced | passed |
| upgrade-consistency | failed |
| monitoring | passed |
| operator-self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| scheduled-backup | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring | passed |
| recreate | passed |
| monitoring-2-0 | passed |
| restore-to-encrypted-cluster | passed |
| affinity | passed |
| demand-backup | passed |
| one-pod | passed |
| scheduled-backup | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| storage | passed |
| users | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| tls-issue-self | passed |
| scaling | passed |
| operator-self-healing | passed |
| tls-issue-cert-manager | passed |
| scaling-proxysql | passed |
| tls-issue-cert-manager-ref | passed |
| upgrade | passed |
| upgrade-consistency | failed |
| big-data | passed |
| demand-backup-encrypted-with-tls | passed |
| security-context | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| haproxy | failed |
| big-data | passed |
| scaling | passed |
| recreate | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| upgrade-consistency | failed |
| monitoring | passed |
| demand-backup | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | failed |
| affinity | passed |
| one-pod | passed |
| operator-self-healing | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| scheduled-backup | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| haproxy | failed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-encrypted-with-tls | passed |
| big-data | passed |
| scaling | passed |
| scaling-proxysql | passed |
| upgrade | passed |
| upgrade-consistency | failed |
| init-deploy | passed |
| limits | passed |
| monitoring | passed |
| monitoring-2-0 | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| security-context | passed |

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| big-data | passed |
| recreate | passed |
| scaling | passed |
| storage | passed |
| init-deploy | passed |
| self-healing | passed |
| scaling-proxysql | passed |
| upgrade | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring | passed |
| upgrade-consistency | failed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| demand-backup | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| scheduled-backup | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | passed |

**Review by delgod — APPROVED** [review]

**Pull request merged**
