### PR TITLE
K8SPXC-811 fix haproxy status

### PR DESCRIPTION
**Pull request by hors**
[K8SPXC-798](https://jira.percona.com/browse/K8SPXC-798) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/919/commits/1f146950adca39742d40e56c0bf4504d999635ff
image: `perconalab/percona-xtradb-cluster-operator:PR-919-1f146950`

**Review by delgod — DISMISSED** [review]

**Review by egegunes — APPROVED** [review]

**Review by tplavcic — CHANGES_REQUESTED** [review]
As discussed `kubectl scale` should be fixed also under this ticket.

**Comment by hors** [comment]
> As discussed `kubectl scale` should be fixed also under this ticket.

yes, you are right 
fix https://github.com/percona/percona-xtradb-cluster-operator/pull/919/commits/860803ca75b117499e8de2db2477d8fa81052a7b

**Review by delgod — APPROVED** [review]

**Review by tplavcic — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| recreate | passed |
| scaling | passed |
| big-data | failed |
| haproxy | passed |
| scheduled-backup | passed |
| storage | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| self-healing-advanced | passed |
| affinity | passed |
| one-pod | passed |
| self-healing-advanced-chaos | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| operator-self-healing | passed |
| pitr | passed |
| upgrade-consistency | passed |
| operator-self-healing-chaos | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/919/commits/860803ca75b117499e8de2db2477d8fa81052a7b
image: `perconalab/percona-xtradb-cluster-operator:PR-919-860803ca`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| init-deploy | passed |
| demand-backup | passed |
| limits | passed |
| pitr | passed |
| monitoring-2-0 | passed |
| demand-backup-encrypted-with-tls | passed |
| affinity | passed |
| one-pod | passed |
| big-data | passed |
| auto-tuning | passed |
| scaling | passed |
| proxysql-sidecar-res-limits | passed |
| scaling-proxysql | passed |
| users | passed |
| security-context | passed |
| tls-issue-self | passed |
| scheduled-backup | passed |
| storage | passed |
| tls-issue-cert-manager | passed |
| self-healing | passed |
| tls-issue-cert-manager-ref | passed |
| self-healing-chaos | passed |
| validation-hook | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-haproxy | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/919/commits/860803ca75b117499e8de2db2477d8fa81052a7b
image: `perconalab/percona-xtradb-cluster-operator:PR-919-860803ca`

**Pull request merged**
