### PR TITLE
K8SPXC-895 - Update versions after 1.10.0 release

### PR DESCRIPTION
**Pull request by tplavcic**
[K8SPXC-895](https://jira.percona.com/browse/K8SPXC-895) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| big-data | passed |
| scheduled-backup | passed |
| haproxy | passed |
| recreate | passed |
| upgrade-haproxy | failed |
| scaling | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| affinity | passed |
| upgrade-proxysql | failed |
| one-pod | passed |
| pitr | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | failed |
| demand-backup-encrypted-with-tls | failed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1072/commits/360aa211e91d741a85240327912f68ee10d5cf78
image: `perconalab/percona-xtradb-cluster-operator:PR-1072-360aa211`

**Review by hors — DISMISSED** [review]

**Review by delgod — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scheduled-backup | passed |
| recreate | failed |
| upgrade-haproxy | failed |
| big-data | failed |
| storage | passed |
| haproxy | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| security-context | passed |
| limits | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| affinity | passed |
| upgrade-proxysql | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| smart-update | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | failed |
| restore-to-encrypted-cluster | failed |
| validation-hook | passed |
| upgrade-consistency | failed |
| demand-backup | failed |
| pitr | failed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1072/commits/6594f4ccded45abb151c87fe0b7a5c61549685a5
image: `perconalab/percona-xtradb-cluster-operator:PR-1072-6594f4cc`

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | passed |
| storage | passed |
| upgrade-haproxy | failed |
| scaling | passed |
| recreate | passed |
| big-data | passed |
| haproxy | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| affinity | passed |
| upgrade-proxysql | failed |
| one-pod | passed |
| pitr | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| smart-update | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1072/commits/d3a2bd9e09ef8d0f512c9e23f5a80fe34abd11e5
image: `perconalab/percona-xtradb-cluster-operator:PR-1072-d3a2bd9e`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| init-deploy | passed |
| scaling | passed |
| scheduled-backup | passed |
| recreate | passed |
| upgrade-haproxy | failed |
| limits | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| monitoring-2-0 | passed |
| security-context | passed |
| demand-backup | passed |
| affinity | passed |
| pitr | passed |
| big-data | passed |
| one-pod | passed |
| demand-backup-encrypted-with-tls | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| storage | passed |
| tls-issue-cert-manager | passed |
| self-healing | passed |
| tls-issue-cert-manager-ref | passed |
| self-healing-chaos | passed |
| validation-hook | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-proxysql | failed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/1072/commits/d3a2bd9e09ef8d0f512c9e23f5a80fe34abd11e5
image: `perconalab/percona-xtradb-cluster-operator:PR-1072-d3a2bd9e`

**Pull request merged**
