### PR TITLE
K8SPXC-585 Move users logic after delete

### PR DESCRIPTION
**Pull request by nonemax**
[K8SPXC-585](https://jira.percona.com/browse/K8SPXC-585) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| scaling | passed |
| upgrade-haproxy | passed |
| storage | passed |
| haproxy | passed |
| recreate | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| self-healing | failed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| self-healing-advanced | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| operator-self-healing | passed |
| users | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| upgrade-consistency | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| scheduled-backup | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/845/commits/bd925c9551284d52350c6f3058a69eef0cc3bb85
image: `perconalab/percona-xtradb-cluster-operator:PR-845-bd925c95`

**Review by blez — DISMISSED** [review]

**Review by hors — APPROVED** [review]

**Review by hors — CHANGES_REQUESTED** [review]
@nonemax  please don't ignore the failed tests you can just fix it
e.g. self-healing test:
```
-admin-version	2.0.15-percona-1.1
+admin-version	2.0.17-percona-1.1
```

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| scaling | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| limits | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| big-data | passed |
| storage | passed |
| auto-tuning | passed |
| self-healing | failed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-haproxy | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/845/commits/bd925c9551284d52350c6f3058a69eef0cc3bb85
image: `perconalab/percona-xtradb-cluster-operator:PR-845-bd925c95`

**Review by qJkee — APPROVED** [review]

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| recreate | passed |
| storage | passed |
| scaling | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| self-healing | passed |
| scaling-proxysql | failed |
| init-deploy | passed |
| upgrade-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| demand-backup | passed |
| affinity | passed |
| operator-self-healing | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| pitr | passed |
| upgrade-consistency | passed |
| security-context | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| demand-backup-encrypted-with-tls | failed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/845/commits/373c46e6c6bee20a59a79327b43298c1fb642e95
image: `perconalab/percona-xtradb-cluster-operator:PR-845-373c46e6`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/845/commits/373c46e6c6bee20a59a79327b43298c1fb642e95
image: `perconalab/percona-xtradb-cluster-operator:PR-845-373c46e6`

**Review by blez — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| big-data | passed |
| pitr | passed |
| storage | passed |
| demand-backup-encrypted-with-tls | passed |
| self-healing | passed |
| upgrade-haproxy | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| security-context | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| scheduled-backup | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/845/commits/373c46e6c6bee20a59a79327b43298c1fb642e95
image: `perconalab/percona-xtradb-cluster-operator:PR-845-373c46e6`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| haproxy | passed |
| demand-backup | passed |
| init-deploy | passed |
| pitr | passed |
| limits | passed |
| demand-backup-encrypted-with-tls | passed |
| monitoring-2-0 | passed |
| scheduled-backup | passed |
| affinity | passed |
| big-data | passed |
| one-pod | passed |
| auto-tuning | passed |
| storage | passed |
| proxysql-sidecar-res-limits | passed |
| self-healing | passed |
| users | passed |
| scaling | passed |
| self-healing-advanced | passed |
| scaling-proxysql | passed |
| tls-issue-self | passed |
| operator-self-healing | passed |
| security-context | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-haproxy | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/845/commits/373c46e6c6bee20a59a79327b43298c1fb642e95
image: `perconalab/percona-xtradb-cluster-operator:PR-845-373c46e6`

**Pull request merged**
