### PR TITLE
K8SPXC-722 init adopters commit

### PR DESCRIPTION
**Pull request by spron-in**
[K8SPXC-722](https://jira.percona.com/browse/K8SPXC-722) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by fiowro — APPROVED** [review]
lgtm!

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| storage | passed |
| recreate | passed |
| big-data | passed |
| haproxy | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| operator-self-healing | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | failed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/854/commits/8bce1e0b1de9f2da44f55b33c38332a28e099eab
image: `perconalab/percona-xtradb-cluster-operator:PR-854-8bce1e0b`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| scaling | passed |
| scheduled-backup | passed |
| big-data | passed |
| storage | passed |
| haproxy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| init-deploy | failed |
| security-context | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | passed |
| smart-update | passed |
| operator-self-healing | passed |
| upgrade-consistency | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/854/commits/9e604ba071c99726da31e027b2f66dae98327fd6
image: `perconalab/percona-xtradb-cluster-operator:PR-854-9e604ba0`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| scaling | passed |
| scaling-proxysql | passed |
| big-data | passed |
| security-context | passed |
| haproxy | passed |
| storage | passed |
| init-deploy | passed |
| self-healing | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| recreate | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| restore-to-encrypted-cluster | passed |
| users | passed |
| demand-backup | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| pitr | failed |
| validation-hook | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/854/commits/9e604ba071c99726da31e027b2f66dae98327fd6
image: `perconalab/percona-xtradb-cluster-operator:PR-854-9e604ba0`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| init-deploy | passed |
| scaling | passed |
| limits | passed |
| scaling-proxysql | passed |
| big-data | passed |
| scheduled-backup | passed |
| monitoring-2-0 | passed |
| security-context | passed |
| recreate | passed |
| affinity | passed |
| restore-to-encrypted-cluster | passed |
| one-pod | passed |
| auto-tuning | passed |
| demand-backup | passed |
| upgrade-haproxy | passed |
| proxysql-sidecar-res-limits | passed |
| storage | passed |
| pitr | failed |
| users | passed |
| self-healing | passed |
| tls-issue-self | passed |
| self-healing-advanced | passed |
| tls-issue-cert-manager | passed |
| operator-self-healing | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/854/commits/9e604ba071c99726da31e027b2f66dae98327fd6
image: `perconalab/percona-xtradb-cluster-operator:PR-854-9e604ba0`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| haproxy | passed |
| storage | passed |
| init-deploy | passed |
| self-healing | passed |
| limits | passed |
| self-healing-advanced | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| scaling-proxysql | passed |
| affinity | passed |
| security-context | passed |
| one-pod | passed |
| auto-tuning | passed |
| recreate | passed |
| proxysql-sidecar-res-limits | passed |
| restore-to-encrypted-cluster | passed |
| users | passed |
| demand-backup | passed |
| tls-issue-self | passed |
| pitr | failed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-haproxy | passed |
| scheduled-backup | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/854/commits/9e604ba071c99726da31e027b2f66dae98327fd6
image: `perconalab/percona-xtradb-cluster-operator:PR-854-9e604ba0`

**Pull request merged**
