### PR TITLE
K8SPXC-808 - Fix cleanup of previous chaos-mesh installation

### PR DESCRIPTION
**Pull request by tplavcic**
[K8SPXC-808](https://jira.percona.com/browse/K8SPXC-808) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/917/commits/8ce5c26f9b1c9b8c97177af199b25919b64cf806
image: `perconalab/percona-xtradb-cluster-operator:PR-917-8ce5c26f`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| haproxy | passed |
| scaling-proxysql | passed |
| init-deploy | passed |
| security-context | passed |
| limits | passed |
| monitoring-2-0 | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/917/commits/8ce5c26f9b1c9b8c97177af199b25919b64cf806
image: `perconalab/percona-xtradb-cluster-operator:PR-917-8ce5c26f`

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| big-data | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/917/commits/8ce5c26f9b1c9b8c97177af199b25919b64cf806
image: `perconalab/percona-xtradb-cluster-operator:PR-917-8ce5c26f`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/917/commits/8ce5c26f9b1c9b8c97177af199b25919b64cf806
image: `perconalab/percona-xtradb-cluster-operator:PR-917-8ce5c26f`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| scaling | passed |
| big-data | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/917/commits/8ce5c26f9b1c9b8c97177af199b25919b64cf806
image: `perconalab/percona-xtradb-cluster-operator:PR-917-8ce5c26f`

**Review by hors — APPROVED** [review]

**Pull request merged**
