### PR TITLE
K8SPXC-253 roll out pxc annotation updates

### PR DESCRIPTION
**Pull request by ThoTischner**
[K8SPXC-253](https://jira.percona.com/browse/K8SPXC-253)

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster-operator?pullRequest=535) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster-operator?pullRequest=535) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtradb-cluster-operator?pullRequest=535) it.</sub>

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| big-data | failed |
| recreate | passed |
| storage | failed |
| init-deploy | passed |
| self-healing | failed |
| scaling-proxysql | passed |
| limits | passed |
| restore-to-encrypted-cluster | passed |
| self-healing-advanced | passed |
| upgrade | passed |
| monitoring | failed |
| operator-self-healing | passed |
| monitoring-2-0 | failed |
| upgrade-consistency | failed |
| affinity | failed |
| demand-backup | passed |
| one-pod | passed |
| security-context | passed |
| auto-tuning | passed |
| scheduled-backup | failed |
| proxysql-sidecar-res-limits | passed |
| demand-backup-encrypted-with-tls | passed |
| users | passed |

**Comment by qJkee** [comment]
Hey @ThoTischner 
Did you test it for deletion?
I mean add annotation to `cr.yaml`, apply it, wait for rollout, delete annotation from `cr.yaml` and apply it again.

**Comment by ThoTischner** [comment]
@qJkee I will test this scenario and come back to you ;)

**Comment by delgod** [comment]
Hi @ThoTischner,

I think it is also needed to change `deploy` function inside `pkg/controller/pxc/controller.go`
reason - annotation should be created on the first reconcile loop.

**Comment by ThoTischner** [comment]
> Hi @ThoTischner,
> 
> I think it is also needed to change `deploy` function inside `pkg/controller/pxc/controller.go`
> reason - annotation should be created on the first reconcile loop.

Hey @delgod,

this seems to be already working, cause we use velero to backup the data and set velero hook annotations on the pxc pods to backup.
Never had problems with that ;)

**Comment by ThoTischner** [comment]
@delgod 
Tested it locally, so it is in fact already working.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| big-data | passed |
| scaling-proxysql | passed |
| upgrade | passed |
| upgrade-consistency | failed |
| init-deploy | passed |
| limits | passed |
| monitoring | failed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| scheduled-backup | failed |
| storage | failed |
| self-healing | failed |
| monitoring-2-0 | failed |
| security-context | passed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| demand-backup-encrypted-with-tls | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |

**Review by tplavcic — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| scheduled-backup | failed |
| storage | failed |
| big-data | passed |
| scaling | passed |
| scaling-proxysql | passed |
| upgrade | passed |
| upgrade-consistency | failed |
| init-deploy | passed |
| limits | passed |
| monitoring | failed |
| self-healing | failed |
| demand-backup-encrypted-with-tls | passed |
| security-context | passed |
| monitoring-2-0 | failed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| storage | failed |
| scaling | passed |
| scaling-proxysql | passed |
| upgrade | passed |
| upgrade-consistency | failed |
| recreate | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| demand-backup | passed |
| monitoring | failed |
| scheduled-backup | failed |
| self-healing | failed |
| demand-backup-encrypted-with-tls | passed |
| security-context | passed |
| monitoring-2-0 | failed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |

**Review by tplavcic — APPROVED** [review]

**Comment by s1msn** [comment]
Hi there!
Are there any updates regarding this PR?
We would really love to see this feature merged.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| big-data | passed |
| init-deploy | passed |
| scheduled-backup | failed |
| limits | passed |
| monitoring | failed |
| scaling | passed |
| scaling-proxysql | passed |
| upgrade | passed |
| upgrade-consistency | failed |
| self-healing | failed |
| security-context | passed |
| monitoring-2-0 | failed |
| demand-backup-encrypted-with-tls | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| affinity | failed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |

**Review by delgod — APPROVED** [review]

**Pull request merged**
