### PR TITLE
K8SPXC-645: improve pitr

### PR DESCRIPTION
**Pull request by qJkee**
[K8SPXC-645](https://jira.percona.com/browse/K8SPXC-645) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

This PR have following improvements :

1. Now 2 clusters can write to one bucket without any errors.
2. When we have a "gap" between binlogs, we will write a log message about it to the user
3. We always read last gtid set from s3 instead of storing it

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/790/commits/c347af8b393e6eb473e1c367ca64933553abe7df
image: `perconalab/percona-xtradb-cluster-operator:PR-790-c347af8b`

**Review by delgod — CHANGES_REQUESTED** [review]

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| big-data | passed |
| storage | passed |
| scaling | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| upgrade-proxysql | passed |
| security-context | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| self-healing-advanced | failed |
| one-pod | passed |
| auto-tuning | passed |
| pitr | passed |
| proxysql-sidecar-res-limits | failed |
| demand-backup-encrypted-with-tls | passed |
| operator-self-healing | passed |
| users | passed |
| upgrade-consistency | passed |
| scheduled-backup | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/790/commits/01f0f1f6b34918cad9a12f035592a9c631544670
image: `perconalab/percona-xtradb-cluster-operator:PR-790-01f0f1f6`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| big-data | passed |
| storage | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| haproxy | passed |
| self-healing | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| limits | passed |
| upgrade-proxysql | passed |
| self-healing-advanced | failed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| affinity | passed |
| smart-update | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| operator-self-healing | passed |
| users | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| scheduled-backup | failed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/790/commits/7e5a610410128cdb447dde12677857f623d593b4
image: `perconalab/percona-xtradb-cluster-operator:PR-790-7e5a6104`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| big-data | passed |
| storage | passed |
| self-healing | passed |
| haproxy | passed |
| self-healing-advanced | failed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| scaling-proxysql | passed |
| affinity | passed |
| security-context | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| operator-self-healing | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/790/commits/7e5a610410128cdb447dde12677857f623d593b4
image: `perconalab/percona-xtradb-cluster-operator:PR-790-7e5a6104`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | failed |
| big-data | passed |
| upgrade-haproxy | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| affinity | passed |
| scaling-proxysql | passed |
| one-pod | passed |
| security-context | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| operator-self-healing | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/790/commits/7e5a610410128cdb447dde12677857f623d593b4
image: `perconalab/percona-xtradb-cluster-operator:PR-790-7e5a6104`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| big-data | passed |
| haproxy | passed |
| init-deploy | passed |
| storage | passed |
| limits | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| self-healing-advanced | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| operator-self-healing | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/790/commits/7e5a610410128cdb447dde12677857f623d593b4
image: `perconalab/percona-xtradb-cluster-operator:PR-790-7e5a6104`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-haproxy | passed |
| storage | passed |
| self-healing | passed |
| self-healing-advanced | failed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| big-data | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| operator-self-healing | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/790/commits/7e5a610410128cdb447dde12677857f623d593b4
image: `perconalab/percona-xtradb-cluster-operator:PR-790-7e5a6104`

**Review by nonemax — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| storage | passed |
| big-data | passed |
| recreate | passed |
| scaling | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| scaling-proxysql | passed |
| self-healing-advanced | failed |
| demand-backup | passed |
| security-context | passed |
| pitr | passed |
| haproxy | passed |
| demand-backup-encrypted-with-tls | passed |
| init-deploy | passed |
| scheduled-backup | failed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| operator-self-healing | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/790/commits/7e5a610410128cdb447dde12677857f623d593b4
image: `perconalab/percona-xtradb-cluster-operator:PR-790-7e5a6104`

**Pull request merged**
