### PR TITLE
K8SPXC-642: Update labels in sts template

### PR DESCRIPTION
**Pull request by blez**
[K8SPXC-642](https://jira.percona.com/browse/K8SPXC-642) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/849/commits/18313c196a076e4f73f9a7d32d880e7481f3af9d
image: `perconalab/percona-xtradb-cluster-operator:PR-849-18313c19`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/849/commits/18313c196a076e4f73f9a7d32d880e7481f3af9d
image: `perconalab/percona-xtradb-cluster-operator:PR-849-18313c19`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| storage | passed |
| haproxy | passed |
| big-data | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| self-healing | failed |
| init-deploy | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| scheduled-backup | failed |
| monitoring-2-0 | passed |
| smart-update | failed |
| affinity | passed |
| self-healing-advanced | passed |
| one-pod | passed |
| auto-tuning | passed |
| operator-self-healing | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | failed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/849/commits/18313c196a076e4f73f9a7d32d880e7481f3af9d
image: `perconalab/percona-xtradb-cluster-operator:PR-849-18313c19`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| storage | passed |
| self-healing | failed |
| big-data | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| upgrade-haproxy | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| scheduled-backup | failed |
| upgrade-proxysql | passed |
| smart-update | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/849/commits/18313c196a076e4f73f9a7d32d880e7481f3af9d
image: `perconalab/percona-xtradb-cluster-operator:PR-849-18313c19`

**Review by qJkee — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| haproxy | passed |
| recreate | passed |
| init-deploy | passed |
| restore-to-encrypted-cluster | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| pitr | passed |
| affinity | passed |
| demand-backup-encrypted-with-tls | passed |
| one-pod | passed |
| scheduled-backup | failed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| storage | passed |
| users | passed |
| self-healing | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| big-data | passed |
| upgrade-haproxy | passed |
| upgrade-proxysql | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/849/commits/18313c196a076e4f73f9a7d32d880e7481f3af9d
image: `perconalab/percona-xtradb-cluster-operator:PR-849-18313c19`

**Pull request merged**
