### PR TITLE
K8SPSMDB-431: Add finalizer to on-demand backup spec

### PR DESCRIPTION
**Pull request by blez**
[K8SPSMDB-431](https://jira.percona.com/browse/K8SPSMDB-431) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Comment by tplavcic** [comment]
@delgod @blez This is already added on the release branch: https://github.com/percona/percona-xtradb-cluster-operator/blob/release-1.8.0/deploy/backup/backup.yaml#L5 but there it is commented since the default `storageName: fs-pvc`

**Comment by blez** [comment]
@delgod , what should we do in such case?

**Comment by delgod** [comment]
is the finalizer works fine for PVC storage?
it shouldn't be any issues with PVC storage

**Review by delgod — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| big-data | passed |
| storage | passed |
| recreate | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| self-healing | failed |
| init-deploy | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| self-healing-advanced | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| operator-self-healing | failed |
| pitr | failed |
| proxysql-sidecar-res-limits | failed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/846/commits/6246d51c9d65c273f8b369b1e551d91e755b3f19
image: `perconalab/percona-xtradb-cluster-operator:PR-846-6246d51c`

**Review by qJkee — APPROVED** [review]

**Comment by blez** [comment]
@delgod @tplavcic 
I've added the logic which checks if S3 finalizer was set for non S3 backup and remove it in such case.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| upgrade-haproxy | passed |
| storage | passed |
| recreate | passed |
| haproxy | passed |
| scaling | passed |
| self-healing | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| affinity | passed |
| operator-self-healing | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| scheduled-backup | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/846/commits/48a11fce16afeb3dd855e6b51fd471d3760db1d6
image: `perconalab/percona-xtradb-cluster-operator:PR-846-48a11fce`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| recreate | passed |
| big-data | passed |
| storage | passed |
| haproxy | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| restore-to-encrypted-cluster | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| operator-self-healing | failed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| pitr | passed |
| users | failed |
| demand-backup-encrypted-with-tls | passed |
| upgrade-consistency | passed |
| scheduled-backup | failed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/846/commits/aa556f0d30b4cfaa61d2d864d5308b031b26477b
image: `perconalab/percona-xtradb-cluster-operator:PR-846-aa556f0d`

**Review by qJkee — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| big-data | passed |
| storage | passed |
| self-healing | passed |
| upgrade-haproxy | passed |
| self-healing-advanced | passed |
| operator-self-healing | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/846/commits/aa556f0d30b4cfaa61d2d864d5308b031b26477b
image: `perconalab/percona-xtradb-cluster-operator:PR-846-aa556f0d`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/846/commits/aa556f0d30b4cfaa61d2d864d5308b031b26477b
image: `perconalab/percona-xtradb-cluster-operator:PR-846-aa556f0d`

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/846/commits/aa556f0d30b4cfaa61d2d864d5308b031b26477b
image: `perconalab/percona-xtradb-cluster-operator:PR-846-aa556f0d`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| upgrade-haproxy | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| storage | passed |
| one-pod | passed |
| self-healing | passed |
| auto-tuning | passed |
| self-healing-advanced | passed |
| proxysql-sidecar-res-limits | passed |
| operator-self-healing | passed |
| users | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| scaling | passed |
| demand-backup | passed |
| scaling-proxysql | passed |
| pitr | passed |
| security-context | passed |
| demand-backup-encrypted-with-tls | passed |
| scheduled-backup | passed |
| big-data | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/846/commits/aa556f0d30b4cfaa61d2d864d5308b031b26477b
image: `perconalab/percona-xtradb-cluster-operator:PR-846-aa556f0d`

**Pull request merged**
