### PR TITLE
K8SPXC-784: parameterize operator deployment name with env var from helm chart

### PR DESCRIPTION
**Pull request by jhgaylor**
[K8SPXC-784](https://jira.percona.com/browse/K8SPXC-784) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

This is written to match the [helm chart](https://github.com/percona/percona-helm-charts/blob/main/charts/pxc-operator/templates/deployment.yaml#L49-L50)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | passed |
| storage | passed |
| upgrade-haproxy | passed |
| scaling | passed |
| big-data | passed |
| recreate | passed |
| haproxy | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| init-deploy | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-chaos | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| self-healing-advanced | passed |
| affinity | passed |
| one-pod | passed |
| self-healing-advanced-chaos | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | failed |
| operator-self-healing | passed |
| upgrade-consistency | passed |
| operator-self-healing-chaos | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | failed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/903/commits/088c2f0e8f3092d0afd25673ed13da6185555cd1
image: `perconalab/percona-xtradb-cluster-operator:PR-903-088c2f0e`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| big-data | passed |
| scheduled-backup | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/903/commits/088c2f0e8f3092d0afd25673ed13da6185555cd1
image: `perconalab/percona-xtradb-cluster-operator:PR-903-088c2f0e`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | passed |
| big-data | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| one-pod | passed |
| upgrade-haproxy | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| users | passed |
| recreate | passed |
| restore-to-encrypted-cluster | passed |
| demand-backup | passed |
| pitr | passed |
| demand-backup-encrypted-with-tls | passed |
| scaling | passed |
| scaling-proxysql | passed |
| security-context | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| self-healing-advanced | passed |
| self-healing-advanced-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |

commit: https://github.com/percona/percona-xtradb-cluster-operator/pull/903/commits/088c2f0e8f3092d0afd25673ed13da6185555cd1
image: `perconalab/percona-xtradb-cluster-operator:PR-903-088c2f0e`

**Review by egegunes — APPROVED** [review]
Thank you for the contribution!

**Review by qJkee — APPROVED** [review]

**Review by delgod — APPROVED** [review]

**Pull request merged**
