### PR TITLE
K8SPXC-586 Some tests fixes

### PR DESCRIPTION
**Pull request by cap1984**
[K8SPXC-586](https://jira.percona.com/browse/K8SPXC-586) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

- Monitoring 2.0 test was adapted for openshift and latest PMM server
- Upgrade proxysql test was updated with missing file for openshift

### CODE REVIEW

**Review by tplavcic — APPROVED** [review]

**Review by tplavcic — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| big-data | passed |
| scaling | passed |
| recreate | passed |
| haproxy | passed |
| storage | passed |
| self-healing | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| security-context | passed |
| upgrade-proxysql | passed |
| limits | passed |
| restore-to-encrypted-cluster | passed |
| monitoring-2-0 | passed |
| smart-update | passed |
| affinity | passed |
| demand-backup | passed |
| self-healing-advanced | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| scheduled-backup | passed |
| users | passed |
| operator-self-healing | passed |
| tls-issue-self | passed |
| demand-backup-encrypted-with-tls | failed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| upgrade-consistency | passed |
| validation-hook | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| big-data | passed |
| scaling | passed |
| haproxy | passed |
| upgrade-haproxy | passed |
| recreate | passed |
| self-healing | passed |
| init-deploy | passed |
| scaling-proxysql | passed |
| security-context | passed |
| restore-to-encrypted-cluster | passed |
| upgrade-proxysql | passed |
| limits | passed |
| self-healing-advanced | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| smart-update | passed |
| operator-self-healing | passed |
| affinity | passed |
| one-pod | passed |
| auto-tuning | passed |
| proxysql-sidecar-res-limits | passed |
| scheduled-backup | passed |
| users | passed |
| upgrade-consistency | passed |
| tls-issue-self | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| demand-backup-encrypted-with-tls | failed |

**Review by hors — APPROVED** [review]

**Comment by JNKPercona** [comment]
PXC operator docker - perconalab/percona-xtradb-cluster-operator:PR-712-50769a24

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-haproxy | passed |
| haproxy | passed |
| init-deploy | passed |
| limits | passed |
| monitoring-2-0 | passed |
| affinity | passed |
| recreate | passed |
| one-pod | passed |
| storage | passed |
| scaling | passed |
| restore-to-encrypted-cluster | passed |
| auto-tuning | passed |
| scaling-proxysql | passed |
| self-healing | passed |
| demand-backup | passed |
| proxysql-sidecar-res-limits | passed |
| security-context | passed |
| self-healing-advanced | passed |
| scheduled-backup | passed |
| users | passed |
| operator-self-healing | passed |
| demand-backup-encrypted-with-tls | passed |
| tls-issue-self | passed |
| big-data | passed |
| tls-issue-cert-manager | passed |
| tls-issue-cert-manager-ref | passed |
| validation-hook | passed |
| upgrade-proxysql | passed |
| smart-update | passed |
| upgrade-consistency | passed |
| pitr | passed |

**Pull request merged**
